import xlsxwriter
from datetime import datetime


def createSpecSheet(case_data, units, other, act_):
    workbook = xlsxwriter.Workbook('specsheet.xlsx')
    for i in range(len(case_data)):
        print(i)
        current_datetime = datetime.today().date().timetuple()
        fluid_state = case_data[i][0][16]
        print(fluid_state)
        if fluid_state.lower() == 'liquid':
            data_valve = ['Specific Gravity', 'Kinematic Viscosity', 'Vapor Pressure', 'Liquid Pr. Recovery Factor, Fl']
        else:
            data_valve = ['Molecular Weight', 'Specific Heat Ratio', 'Compressibility Factor',
                          'Pressure Drop Ratio (Xt)']

        if other[i][21] == 'globe':
            data_trim = ['CV/Characteristic', 'Balancing', 'Trim Material', 'Soft Seat Material', '%', 'm/s']
        else:
            data_trim = ['CV/Characteristic', 'Shaft Material', 'Disc Material', 'Seat Material', 'degree', 'mach']
        str_current_datetime = str(current_datetime)
        a__ = datetime.now()
        a_ = a__.strftime("%a, %d %b %Y %H-%M-%S")
        worksheet = workbook.add_worksheet(f"sheet-{int(i) + 1}")
        worksheet.set_paper(9)
        worksheet.fit_to_pages(2, 1)
        worksheet.print_area('A1:L73')
        worksheet.set_margins(0.68, 0.44, 0.32, 0.16)

        bold = workbook.add_format(
            {'align': 'center', 'bold': True, 'bottom': 1, 'top': 1, 'right': 1, 'left': 1, 'border_color': '#B2B2B2',
             'bg_color': '#EFF5F5'})
        bold1 = workbook.add_format(
            {'bold': True, 'bottom': 1, 'top': 1, 'left': 1, 'border_color': '#B2B2B2', 'bg_color': '#EFF5F5'})
        boldc = workbook.add_format(
            {'align': 'left', 'bold': True, 'bottom': 1, 'top': 1, 'right': 1, 'left': 1, 'border_color': '#B2B2B2',
             'bg_color': '#EFF5F5', 'font': 'Arial', 'size': 10})
        br = workbook.add_format({'bottom': 1, 'top': 1, 'right': 1, 'border_color': '#B2B2B2'})
        h1 = workbook.add_format({'bold': True, 'font_size': 12, 'align': 'center', 'font': 'Arial'})
        h2 = workbook.add_format({'bold': 0, 'font_size': 10, 'font': 'Arial'})
        h3 = workbook.add_format({'bold': 0, 'font_size': 9, 'font': 'Arial'})
        f1 = workbook.add_format({'bold': 0, 'font_size': 9, 'font': 'Arial', 'align': 'right'})
        f2 = workbook.add_format({'bold': 0, 'font_size': 9, 'font': 'Arial', 'align': 'left'})

        cell_format1 = workbook.add_format(
            {'bottom': 1, 'top': 1, 'border_color': '#B2B2B2', 'font_size': 9, 'font': 'Arial'})
        cell_format = workbook.add_format(
            {'bold': 0, 'font_color': 'black', 'font': 'Arial', 'font_size': 9, 'bottom': 1, 'top': 1, 'right': 1,
             'left': 1, 'align': 'left',
             'border_color': '#B2B2B2'})

        cell_format2 = workbook.add_format(
            {'bold': 0, 'align': 'center', 'font_color': 'black', 'font': 'Arial', 'font_size': 9, 'bottom': 1,
             'top': 1,
             'right': 1, 'left': 1, 'border_color': '#B2B2B2'})

        column_width = [{'name': 'A1:A73', 'size': 5}, {'name': 'B1:B73', 'size': 24}, {'name': 'C1:C73', 'size': 10},
                        {'name': 'D1:D73', 'size': 12},
                        {'name': 'E1:E73', 'size': 7}, {'name': 'F1:F73', 'size': 5}, {'name': 'G1:G73', 'size': 12},
                        {'name': 'H1:H73', 'size': 12},
                        {'name': 'I1:I73', 'size': 6}, {'name': 'J1:J73', 'size': 6}, {'name': 'K1:K73', 'size': 5},
                        {'name': 'L1:L73', 'size': 8}]

        for j in column_width:
            worksheet.set_column(j['name'], j['size'])

        # worksheet.set_column('A1:A73', 5)
        # worksheet.set_column('B1:B73', 24)
        # worksheet.set_column('C1:C73', 10)
        # worksheet.set_column('D1:D73', 12)
        # worksheet.set_column('E1:E73', 7)
        # worksheet.set_column('F1:F73', 5)
        # worksheet.set_column('G1:G73', 12)
        # worksheet.set_column('H1:H73', 12)
        # worksheet.set_column('I1:I73', 6)
        # worksheet.set_column('J1:J73', 6)
        # worksheet.set_column('K1:K73', 6)
        # worksheet.set_column('L1:L73', 6)

        worksheet.write('A1', 'Flow Control Commune', h2)
        worksheet.write('A3', '')
        worksheet.merge_range('A4:B4', "Customer", cell_format)
        worksheet.merge_range('A5:B5', "Project", cell_format)
        worksheet.merge_range('A6:B6', "End User", cell_format)
        worksheet.merge_range('A7:B7', "RFQ No", cell_format)
        worksheet.merge_range('A8:B8', "PO No", cell_format)
        worksheet.merge_range('A9:B9', "P & ID Ref  /  Line No", cell_format)
        worksheet.write('A10', '')
        worksheet.write('A11', 'Fluid State / Name', f2)
        worksheet.write('A12', 'Service Description', f2)
        worksheet.write('A13', 'AA', bold)
        worksheet.write('A14', '1', cell_format2)
        worksheet.write('A15', '2', cell_format2)
        worksheet.write('A16', '3', cell_format2)
        worksheet.write('A17', '4', cell_format2)
        worksheet.write('A18', '5', cell_format2)
        worksheet.write('A19', '6', cell_format2)
        worksheet.write('A20', '7', cell_format2)
        worksheet.write('A21', '8', cell_format2)
        worksheet.write('A22', '9', cell_format2)
        worksheet.write('A23', '10', cell_format2)
        worksheet.write('A24', '11', cell_format2)
        worksheet.write('A25', '12', cell_format2)
        worksheet.write('A26', '13', cell_format2)
        worksheet.write('A27', '14', cell_format2)
        worksheet.write('A28', '15', cell_format2)
        # worksheet.write('A29', '')
        worksheet.write('A30', 'BB', bold)
        worksheet.write('A31', '16', cell_format2)
        worksheet.write('A32', '17', cell_format2)
        worksheet.write('A33', '18', cell_format2)
        worksheet.write('A34', '19', cell_format2)
        worksheet.write('A35', '20', cell_format2)
        worksheet.write('A36', 'CC', bold)
        worksheet.write('A37', '21', cell_format2)
        worksheet.write('A38', '22', cell_format2)
        worksheet.write('A39', '23', cell_format2)
        worksheet.write('A40', '24', cell_format2)
        worksheet.write('A41', '25', cell_format2)
        worksheet.write('A42', '26', cell_format2)
        worksheet.write('A43', '27', cell_format2)
        worksheet.write('A44', '28', cell_format2)
        worksheet.write('A45', '29', cell_format2)
        worksheet.write('A46', '30', cell_format2)
        worksheet.write('A47', '31', cell_format2)
        worksheet.write('A48', '32', cell_format2)
        worksheet.write('A49', '33', cell_format2)
        worksheet.write('A50', '34', cell_format2)
        worksheet.write('A51', '35', cell_format2)
        worksheet.write('A52', 'DD', bold)
        worksheet.write('A53', '36', cell_format2)
        worksheet.write('A54', '37', cell_format2)
        worksheet.write('A55', '38', cell_format2)
        worksheet.write('A56', '39', cell_format2)
        worksheet.write('A57', '40', cell_format2)
        worksheet.write('A58', '41', cell_format2)
        worksheet.write('A59', '42', cell_format2)
        worksheet.write('A60', '43', cell_format2)
        worksheet.write('A61', '44', cell_format2)
        worksheet.write('A62', 'HH', bold)
        worksheet.write('A63', '74', cell_format2)
        worksheet.write('A64', '75', cell_format2)
        worksheet.write('A65', '76', cell_format2)
        worksheet.write('A66', '77', cell_format2)
        worksheet.write('A67', '78', cell_format2)
        worksheet.write('A68', '79', cell_format2)
        worksheet.write('A69', '80', cell_format2)
        worksheet.write('A70', '81', cell_format2)
        worksheet.write('A71', '82', cell_format2)
        worksheet.write('A72', '83', cell_format2)

        worksheet.write('B2', '')
        worksheet.write('B3', '')
        worksheet.write('B10', '')
        worksheet.write('B11', '')
        worksheet.write('B12', '')
        worksheet.write('B13', 'Valve Sizing Calculation', boldc)
        worksheet.write('B14', 'Flow Rate', cell_format)
        worksheet.write('B15', 'Inlet Pressure', cell_format)
        worksheet.write('B16', 'Outlet Pressure', cell_format)
        worksheet.write('B17', 'Inlet Temperature', cell_format)
        worksheet.write('B18', data_valve[0], cell_format)
        worksheet.write('B19', data_valve[1], cell_format)
        worksheet.write('B20', data_valve[2], cell_format)
        worksheet.write('B21', data_valve[3], cell_format)
        worksheet.write('B22', 'Calculated Cv', cell_format)
        worksheet.write('B23', 'Percentage Opening / Degree', cell_format)
        worksheet.write('B24', 'Noise level at 1m distance', cell_format)
        worksheet.write('B25', 'Inlet Pipe Velocity', cell_format)
        worksheet.write('B26', 'Outlet Pipe Velocity', cell_format)
        worksheet.write('B27', 'Trim Exit Velocity', cell_format)
        worksheet.write('B31', 'Size, Schedule Inlet', cell_format1)
        worksheet.write('B32', 'Size, Schedule Oulet', cell_format1)
        worksheet.write('B33', 'Insulation', cell_format1)
        worksheet.write('B34', 'Design Pressure', cell_format1)
        worksheet.write('B35', 'Design Temp. Min / Max', cell_format1)
        worksheet.write('B37', 'Valve Mfg / Model No..', cell_format1)
        worksheet.write('B38', 'Size / Rating', cell_format1)
        worksheet.write('B39', 'Body Style', cell_format1)
        worksheet.write('B40', 'Body Material', cell_format1)
        worksheet.write('B41', 'End Connections', cell_format1)
        worksheet.write('B42', 'End Finish / Preparation', cell_format1)
        worksheet.write('B43', 'Body F/F Dim', cell_format1)
        worksheet.write('B44', 'Bonnet Type', cell_format1)
        worksheet.write('B45', 'Bonnet Material', cell_format1)
        worksheet.write('B46', 'Extension dimension', cell_format1)
        worksheet.write('B47', 'Body/Bonnet NDE1', cell_format1)
        worksheet.write('B48', 'Body/Bonnet NDE2', cell_format1)
        worksheet.write('B49', 'Bonnet Bolting', cell_format1)
        worksheet.write('B50', 'Gasket Material', cell_format1)
        worksheet.write('B51', 'Gland Packing', cell_format1)
        worksheet.write('B53', 'Trim Size / Type', cell_format1)
        worksheet.write('B54', data_trim[0], cell_format1)
        worksheet.write('B55', data_trim[1], cell_format1)
        worksheet.write('B56', 'Flow Direction', cell_format1)
        worksheet.write('B57', data_trim[2], cell_format1)
        worksheet.write('B58', data_trim[3], cell_format1)
        worksheet.write('B59', 'Seat Leakage Class', cell_format1)
        worksheet.write('B60', 'Bellows Material', cell_format1)
        worksheet.write('B61', '', cell_format1)

        worksheet.write('C1', 'Control Valve Specification Sheet', h1)
        worksheet.write('C2', '')
        worksheet.write('C3', '')
        print(f"slice/string: {i}")
        worksheet.write('C4', case_data[i][0][-1], cell_format)

        worksheet.write('C5', '', cell_format)
        worksheet.write('C6', '', cell_format)
        worksheet.write('C7', '', cell_format)
        worksheet.write('C8', '', cell_format)
        worksheet.write('C9', '', cell_format)
        worksheet.write('C10', '')
        worksheet.write('C11', 'Liquid / Fuel Oil Gr1 / Bitumen', f2)
        worksheet.write('C12', 'Mixing', f2)
        worksheet.write('C13', 'Units', boldc)
        worksheet.write('C14', '', cell_format)
        worksheet.write('C15', '', cell_format)
        worksheet.write('C16', '', cell_format)
        worksheet.write('C17', '', cell_format)
        worksheet.write('C18', '', cell_format)
        worksheet.write('C19', '', cell_format)
        worksheet.write('C20', '', cell_format)
        worksheet.write('C21', '', cell_format)
        worksheet.write('C22', '', cell_format)
        worksheet.write('C23', '', cell_format)
        worksheet.write('C24', '', cell_format)
        worksheet.write('C25', '', cell_format)
        worksheet.write('C26', '', cell_format)
        worksheet.write('C27', '', cell_format)
        worksheet.write('C30', '', cell_format1)
        worksheet.write('C31', '', cell_format1)
        worksheet.write('C32', '', cell_format1)
        worksheet.write('C33', '', cell_format1)
        # worksheet.write('C34', '', cell_format1)
        # worksheet.write('C35', '', cell_format1)
        worksheet.write('C36', '', cell_format1)
        worksheet.write('C37', '', cell_format1)
        worksheet.write('C38', '', cell_format1)
        worksheet.write('C39', '', cell_format1)
        worksheet.write('C40', '', cell_format1)
        worksheet.write('C41', '', cell_format1)
        worksheet.write('C42', '', cell_format1)
        worksheet.write('C43', '', cell_format1)
        worksheet.write('C44', '', cell_format1)
        worksheet.write('C45', '', cell_format1)
        worksheet.write('C46', '', cell_format1)
        worksheet.write('C47', '', cell_format1)
        worksheet.write('C48', '', cell_format1)
        worksheet.write('C49', '', cell_format1)
        worksheet.write('C50', '', cell_format1)
        worksheet.write('C51', '', cell_format1)
        worksheet.write('C52', '', cell_format1)
        worksheet.write('C53', '', cell_format1)
        worksheet.write('C54', '', cell_format1)
        worksheet.write('C55', '', cell_format1)
        worksheet.write('C56', '', cell_format1)
        worksheet.write('C57', '', cell_format1)
        worksheet.write('C58', '', cell_format1)
        worksheet.write('C59', '', cell_format1)
        worksheet.write('C60', '', cell_format1)
        worksheet.write('C61', '', cell_format1)

        worksheet.write('D2', '')
        worksheet.write('D3', '')
        worksheet.write('D4', '', cell_format)
        worksheet.write('D5', '', cell_format)
        worksheet.write('D6', '', cell_format)
        worksheet.write('D7', '', cell_format)
        worksheet.write('D8', '', cell_format)
        worksheet.write('D9', '', cell_format)
        worksheet.write('D10', '')
        worksheet.write('D11', '')
        worksheet.write('D12', '')
        worksheet.write('D13', 'Case1', boldc)
        worksheet.write('D14', '', cell_format)
        worksheet.write('D15', '', cell_format)
        worksheet.write('D16', '', cell_format)
        worksheet.write('D17', '', cell_format)
        worksheet.write('D18', '', cell_format)
        worksheet.write('D19', '', cell_format)
        worksheet.write('D20', '', cell_format)
        worksheet.write('D21', '', cell_format)
        worksheet.write('D22', '', cell_format)
        worksheet.write('D23', '', cell_format)
        worksheet.write('D24', '', cell_format)
        worksheet.write('D25', '', cell_format)
        worksheet.write('D26', '', cell_format)
        worksheet.write('D27', '', cell_format)
        worksheet.write('D28', 'No Cavitation, Flasing, Noise, High Trim exit velocity', cell_format)
        worksheet.write('D29', '', cell_format1)
        worksheet.write('D30', '', cell_format1)
        worksheet.write('D31', '', cell_format1)
        worksheet.write('D32', '', cell_format1)
        worksheet.write('D33', '', cell_format1)
        worksheet.write('D34', '', cell_format1)
        worksheet.write('D35', '', cell_format1)
        worksheet.write('D36', '', cell_format1)
        worksheet.write('D37', '', cell_format1)
        worksheet.write('D38', '', cell_format1)
        worksheet.write('D39', '', cell_format1)
        worksheet.write('D40', '', cell_format1)
        worksheet.write('D41', '', cell_format1)
        worksheet.write('D42', '', cell_format1)
        worksheet.write('D43', '', cell_format1)
        worksheet.write('D44', '', cell_format1)
        worksheet.write('D45', '', cell_format1)
        worksheet.write('D46', '', cell_format1)
        worksheet.write('D47', '', cell_format1)
        worksheet.write('D48', '', cell_format1)
        worksheet.write('D49', '', cell_format1)
        worksheet.write('D50', '', cell_format1)
        worksheet.write('D51', '', cell_format1)
        worksheet.write('D52', '', cell_format1)
        worksheet.write('D53', '', cell_format1)
        worksheet.write('D54', '', cell_format1)
        worksheet.write('D55', '', cell_format1)
        worksheet.write('D56', '', cell_format1)
        worksheet.write('D57', '', cell_format1)
        worksheet.write('D58', '', cell_format1)
        worksheet.write('D59', '', cell_format1)
        worksheet.write('D60', '', cell_format1)
        worksheet.write('D61', '', cell_format1)

        worksheet.write('E1', '')
        worksheet.write('E2', '')
        worksheet.write('E3', '')
        worksheet.write('E4', '', cell_format)
        worksheet.write('E5', '', cell_format)
        worksheet.write('E6', '', cell_format)
        worksheet.write('E7', '', cell_format)
        worksheet.write('E8', '', cell_format)
        worksheet.write('E9', '', cell_format)
        worksheet.write('E10', '')
        worksheet.write('E11', '')
        worksheet.write('E12', '')
        worksheet.write('E14', '', cell_format)
        worksheet.write('E15', '', cell_format)
        worksheet.write('E16', '', cell_format)
        worksheet.write('E17', '', cell_format)
        worksheet.write('E18', '', cell_format)
        worksheet.write('E19', '', cell_format)
        worksheet.write('E20', '', cell_format)
        worksheet.write('E21', '', cell_format)
        worksheet.write('E22', '', cell_format)
        worksheet.write('E23', '', cell_format)
        worksheet.write('E24', '', cell_format)
        worksheet.write('E25', '', cell_format)
        worksheet.write('E26', '', cell_format)
        worksheet.write('E27', '', cell_format)
        worksheet.write('E30', '', cell_format1)
        worksheet.write('E31', '', cell_format1)
        worksheet.write('E32', '', cell_format1)
        worksheet.write('E33', '', cell_format1)
        worksheet.write('E34', '', cell_format1)
        worksheet.write('E35', '', cell_format1)
        worksheet.write('E36', '', cell_format1)
        worksheet.write('E37', '', cell_format1)
        worksheet.write('E38', '', cell_format1)
        worksheet.write('E39', '', cell_format1)
        worksheet.write('E40', '', cell_format1)
        worksheet.write('E41', '', cell_format1)
        worksheet.write('E42', '', cell_format1)
        worksheet.write('E43', '', cell_format1)
        worksheet.write('E44', '', cell_format1)
        worksheet.write('E45', '', cell_format1)
        worksheet.write('E46', '', cell_format1)
        worksheet.write('E47', '', cell_format1)
        worksheet.write('E48', '', cell_format1)
        worksheet.write('E49', '', cell_format1)
        worksheet.write('E50', '', cell_format1)
        worksheet.write('E51', '', cell_format1)
        worksheet.write('E52', '', cell_format1)
        worksheet.write('E53', '', cell_format1)
        worksheet.write('E54', '', cell_format1)
        worksheet.write('E55', '', cell_format1)
        worksheet.write('E56', '', cell_format1)
        worksheet.write('E57', '', cell_format1)
        worksheet.write('E58', '', cell_format1)
        worksheet.write('E59', '', cell_format1)
        worksheet.write('E60', '', cell_format1)
        worksheet.write('E61', '', cell_format1)

        worksheet.write('F1', '')
        worksheet.write('F2', '')
        worksheet.write('F3', '')
        worksheet.write('F4', '', cell_format)
        worksheet.write('F5', '', cell_format)
        worksheet.write('F6', '', cell_format)
        worksheet.write('F7', '', cell_format)
        worksheet.write('F8', '', cell_format)
        worksheet.write('F9', '', cell_format)
        worksheet.write('F10', '')
        worksheet.write('F11', '')
        worksheet.write('F12', '')
        worksheet.write('F30', 'EE', bold)
        worksheet.write('F31', '45', cell_format2)
        worksheet.write('F32', '46', cell_format2)
        worksheet.write('F33', '47', cell_format2)
        worksheet.write('F34', '48', cell_format2)
        worksheet.write('F35', '49', cell_format2)
        worksheet.write('F36', '50', cell_format2)
        worksheet.write('F37', '51', cell_format2)
        worksheet.write('F38', '52', cell_format2)
        worksheet.write('F39', '53', cell_format2)
        worksheet.write('F40', '54', cell_format2)
        worksheet.write('F41', '55', cell_format2)
        worksheet.write('F42', 'FF', bold)
        worksheet.write('F43', '56', cell_format2)
        worksheet.write('F44', '57', cell_format2)
        worksheet.write('F45', '58', cell_format2)
        worksheet.write('F46', '59', cell_format2)
        worksheet.write('F47', '60', cell_format2)
        worksheet.write('F48', '61', cell_format2)
        worksheet.write('F49', '62', cell_format2)
        worksheet.write('F50', '63', cell_format2)
        worksheet.write('F51', '64', cell_format2)
        worksheet.write('F52', '65', cell_format2)
        worksheet.write('F53', '66', cell_format2)
        worksheet.write('F54', '67', cell_format2)
        worksheet.write('F55', 'GG', bold)
        worksheet.write('F56', '68', cell_format2)
        worksheet.write('F57', '69', cell_format2)
        worksheet.write('F58', '70', cell_format2)
        worksheet.write('F59', '71', cell_format2)
        worksheet.write('F60', '72', cell_format2)
        worksheet.write('F61', '73', cell_format2)

        worksheet.write('G1', '')
        worksheet.write('G2', '')
        worksheet.write('G3', '')
        worksheet.write('G4', 'Quote No', cell_format)
        worksheet.write('G5', 'FCC W/O No', cell_format)
        worksheet.write('G6', 'Serial No', cell_format)
        worksheet.write('G7', 'Tag No', cell_format)
        worksheet.write('G8', 'Qty', cell_format)
        worksheet.write('G9', 'Item No.', cell_format)
        worksheet.write('G10', '')
        worksheet.write('G11', 'Critical Pressure', f2)
        worksheet.write('G12', 'Shutoff Pressure', f2)
        worksheet.write('G13', 'Case3', boldc)
        worksheet.write('G14', '', cell_format)
        worksheet.write('G15', '', cell_format)
        worksheet.write('G16', '', cell_format)
        worksheet.write('G17', '', cell_format)
        worksheet.write('G18', '', cell_format)
        worksheet.write('G19', '', cell_format)
        worksheet.write('G20', '', cell_format)
        worksheet.write('G21', '', cell_format)
        worksheet.write('G22', '', cell_format)
        worksheet.write('G23', '', cell_format)
        worksheet.write('G24', '', cell_format)
        worksheet.write('G25', '', cell_format)
        worksheet.write('G26', '', cell_format)
        worksheet.write('G27', '', cell_format)

        worksheet.write('H2', '')
        worksheet.write('H3', '')
        worksheet.write('H4', str(case_data[i][0][-3]), cell_format)
        worksheet.write('H5', str(case_data[i][0][-2]), cell_format)
        worksheet.write('H6', '', cell_format)
        worksheet.write('H7', str(case_data[i][0][-11]), cell_format)
        worksheet.write('H8', '', cell_format)
        worksheet.write('H9', case_data[i][0][-10], cell_format)
        worksheet.write('H10', '')
        worksheet.write('H11', '')
        worksheet.write('H12', '')
        worksheet.write('H13', 'Case4', boldc)
        worksheet.write('H14', '', cell_format)
        worksheet.write('H15', '', cell_format)
        worksheet.write('H16', '', cell_format)
        worksheet.write('H17', '', cell_format)
        worksheet.write('H18', '', cell_format)
        worksheet.write('H19', '', cell_format)
        worksheet.write('H20', '', cell_format)
        worksheet.write('H21', '', cell_format)
        worksheet.write('H22', '', cell_format)
        worksheet.write('H23', '', cell_format)
        worksheet.write('H24', '', cell_format)
        worksheet.write('H25', '', cell_format)
        worksheet.write('H26', '', cell_format)
        worksheet.write('H27', '', cell_format)
        worksheet.write('H49', '', cell_format)
        worksheet.write('H50', '', cell_format)
        worksheet.write('H51', '', cell_format)
        worksheet.write('H52', '', cell_format)
        worksheet.write('H53', '', cell_format)
        worksheet.write('H54', '', cell_format)
        worksheet.write('H56', '', cell_format)
        worksheet.write('H57', '', cell_format)
        worksheet.write('H58', '', cell_format)
        worksheet.write('H59', '', cell_format)
        worksheet.write('H60', '', cell_format)
        worksheet.write('H61', '', cell_format)

        worksheet.write('I1', '')
        worksheet.write('I2', '')
        worksheet.write('I3', '')
        worksheet.write('I4', '', cell_format)
        worksheet.write('I5', '', cell_format)
        worksheet.write('I6', '', cell_format)
        worksheet.write('I7', '', cell_format)
        worksheet.write('I8', '', cell_format)
        worksheet.write('I9', '', cell_format)
        worksheet.write('I10', '')
        worksheet.write('I11', '')
        worksheet.write('I12', '')
        worksheet.write('I14', '', cell_format)
        worksheet.write('I15', '', cell_format)
        worksheet.write('I16', '', cell_format)
        worksheet.write('I17', '', cell_format)
        worksheet.write('I18', '', cell_format)
        worksheet.write('I19', '', cell_format)
        worksheet.write('I20', '', cell_format)
        worksheet.write('I21', '', cell_format)
        worksheet.write('I22', '', cell_format)
        worksheet.write('I23', '', cell_format)
        worksheet.write('I24', '', cell_format)
        worksheet.write('I25', '', cell_format)
        worksheet.write('I26', '', cell_format)
        worksheet.write('I27', '', cell_format)

        worksheet.insert_image('J1', 'Logo.jpg', {'x_scale': 0.5, 'y_scale': 0.5})
        worksheet.write('J2', '')
        worksheet.write('J3', '')
        worksheet.write('J4', '', cell_format)
        worksheet.write('J5', '', cell_format)
        worksheet.write('J6', '', cell_format)
        worksheet.write('J7', '', cell_format)
        worksheet.write('J8', '', cell_format)
        worksheet.write('J9', '', cell_format)
        worksheet.write('J10', '')
        worksheet.write('J11', '')
        worksheet.write('J12', '')
        worksheet.write('J30', '', cell_format)
        worksheet.write('J31', '', cell_format)
        worksheet.write('J32', '', cell_format)
        worksheet.write('J33', '', cell_format)
        worksheet.write('J34', '', cell_format)
        worksheet.write('J35', '', cell_format)
        worksheet.write('J36', '', cell_format)
        worksheet.write('J37', '', cell_format)
        worksheet.write('J38', '', cell_format)
        worksheet.write('J39', '', cell_format)
        worksheet.write('J40', '', cell_format)
        worksheet.write('J41', '', cell_format1)
        worksheet.write('J42', '', cell_format)
        worksheet.write('J43', '', cell_format)
        worksheet.write('J44', '', cell_format)
        worksheet.write('J45', '', cell_format)
        worksheet.write('J46', '', cell_format)
        worksheet.write('J47', '', cell_format)
        worksheet.write('J48', '', cell_format)
        worksheet.write('J49', '', cell_format)
        worksheet.write('J50', '', cell_format)
        worksheet.write('J51', '', cell_format)
        worksheet.write('J52', '', cell_format)
        worksheet.write('J53', '', cell_format)
        worksheet.write('J54', '', cell_format)
        worksheet.write('J55', '', cell_format)
        worksheet.write('J56', '', cell_format)
        worksheet.write('J57', '', cell_format)
        worksheet.write('J58', '', cell_format)
        worksheet.write('J59', '', cell_format)
        worksheet.write('J60', '', cell_format)
        worksheet.write('J61', '', cell_format)
        worksheet.write('J63', 'By', cell_format)
        worksheet.write('J64', '', cell_format)
        worksheet.write('J65', '', cell_format)
        worksheet.write('J66', '', cell_format)
        worksheet.write('J67', '', cell_format)
        worksheet.write('J68', '', cell_format)
        worksheet.write('J69', '', cell_format)
        worksheet.write('J70', '', cell_format)
        worksheet.write('J71', '', cell_format)
        worksheet.write('J72', '', cell_format)

        worksheet.write('K1', '')
        worksheet.write('K2', '')
        worksheet.write('K3', '')
        worksheet.write('K4', '', cell_format)
        worksheet.write('K5', '', cell_format)
        worksheet.write('K6', '', cell_format)
        worksheet.write('K7', '', cell_format)
        worksheet.write('K8', '', cell_format)
        worksheet.write('K9', '', cell_format)
        worksheet.write('K10', '')
        worksheet.write('K11', '')
        worksheet.write('K12', '')
        worksheet.write('K14', '', cell_format)
        worksheet.write('K15', '', cell_format)
        worksheet.write('K16', '', cell_format)
        worksheet.write('K17', '', cell_format)
        worksheet.write('K18', '', cell_format)
        worksheet.write('K19', '', cell_format)
        worksheet.write('K20', '', cell_format)
        worksheet.write('K21', '', cell_format)
        worksheet.write('K22', '', cell_format)
        worksheet.write('K23', '', cell_format)
        worksheet.write('K24', '', cell_format)
        worksheet.write('K25', '', cell_format)
        worksheet.write('K26', '', cell_format)
        worksheet.write('K27', '', cell_format)

        worksheet.write('K63', 'Rev.', cell_format)
        worksheet.write('K64', '', cell_format)
        worksheet.write('K65', '', cell_format)
        worksheet.write('K66', '', cell_format)
        worksheet.write('K67', '', cell_format)
        worksheet.write('K68', '', cell_format)
        worksheet.write('K69', '', cell_format)
        worksheet.write('K70', '', cell_format)
        worksheet.write('K71', '', cell_format)
        worksheet.write('K72', '', cell_format)

        worksheet.write('L1', '')
        worksheet.write('L2', '')
        worksheet.write('L3', '')
        worksheet.write('L4', '', cell_format)
        worksheet.write('L5', '', cell_format)
        worksheet.write('L6', '', cell_format)
        worksheet.write('L7', '', cell_format)
        worksheet.write('L8', '', cell_format)
        worksheet.write('L9', '', cell_format)
        worksheet.write('L10', '')
        worksheet.write('L11', '')
        worksheet.write('L12', '')
        worksheet.write('L30', '', cell_format)
        worksheet.write('L31', '', cell_format)
        worksheet.write('L32', '', cell_format)
        worksheet.write('L33', '', cell_format)
        worksheet.write('L34', '', cell_format)
        worksheet.write('L35', '', cell_format)
        worksheet.write('L36', '', cell_format)
        worksheet.write('L37', '', cell_format)
        worksheet.write('L38', '', cell_format)
        worksheet.write('L39', '', cell_format)
        worksheet.write('L40', '', cell_format)
        worksheet.write('L41', '', cell_format)
        worksheet.write('L42', '', cell_format)
        worksheet.write('L43', '', cell_format)
        worksheet.write('L44', '', cell_format)
        worksheet.write('L45', '', cell_format)
        worksheet.write('L46', '', cell_format)
        worksheet.write('L47', '', cell_format)
        worksheet.write('L48', '', cell_format)
        worksheet.write('L49', '', cell_format)
        worksheet.write('L50', '', cell_format)
        worksheet.write('L51', '', cell_format)
        worksheet.write('L52', '', cell_format)
        worksheet.write('L53', '', cell_format)
        worksheet.write('L54', '', cell_format)
        worksheet.write('L55', '', cell_format)
        worksheet.write('L56', '', cell_format)
        worksheet.write('L57', '', cell_format)
        worksheet.write('L58', '', cell_format)
        worksheet.write('L59', '', cell_format)
        worksheet.write('L60', '', cell_format)
        worksheet.write('L61', '', cell_format)
        worksheet.write('L62', '', cell_format)
        worksheet.write('L63', 'Date', cell_format)
        worksheet.write('L64', '', cell_format)
        worksheet.write('L65', '', cell_format)
        worksheet.write('L66', '', cell_format)
        worksheet.write('L67', '', cell_format)
        worksheet.write('L68', '', cell_format)
        worksheet.write('L69', '', cell_format)
        worksheet.write('L70', '', cell_format)
        worksheet.write('L71', '', cell_format)
        worksheet.write('L72', '', cell_format)

        worksheet.merge_range('A2:B2', "Chennai, India", h3)
        worksheet.merge_range('G30:L30', "Actuator Data", boldc)

        worksheet.merge_range('B30:E30', "Pipe Line Data", boldc)
        worksheet.merge_range('B36:E36', "Valve Body & Bonnet", boldc)
        worksheet.merge_range('B52:E52', "Valve Trim", boldc)

        worksheet.merge_range('G31:H31', "Actuator Type", cell_format1)

        worksheet.merge_range('G32:H32', "Actuator Model No. / Travel", cell_format1)

        worksheet.merge_range('G33:H33', "Actuator Size / Spring", cell_format1)

        worksheet.merge_range('G34:H34', "Air Fail Action", cell_format1)

        worksheet.merge_range('G35:H35', "Air Supply / Set pressure", cell_format1)

        worksheet.merge_range('G36:H36', "Actuator Orientation", cell_format1)

        worksheet.merge_range('G37:H37', "Handwheel", cell_format1)

        worksheet.merge_range('G38:H38', "Travel Stops", cell_format1)

        worksheet.merge_range('G39:H39', "Tubing make / Size", cell_format1)

        worksheet.merge_range('G40:H40', "Fittings", cell_format1)

        worksheet.merge_range('G41:H41', "Open / Close / Trip Time", cell_format1)

        worksheet.merge_range('G43:H43', "Positioner Mfg / Model", cell_format1)

        worksheet.merge_range('G44:H44', "Signal Action", cell_format1)

        worksheet.merge_range('G45:H45', "AFR Make / Model", cell_format1)

        worksheet.merge_range('G46:H46', "Position Transmitter", cell_format1)

        worksheet.merge_range('G47:H47', "Limit switch / Proximity switch", cell_format1)

        worksheet.merge_range('G48:H48', "Boosters", cell_format1)

        worksheet.merge_range('G49:H49', "Pilot Valves", cell_format1)

        worksheet.merge_range('G50:H50', "Air Lock Relay", cell_format1)

        worksheet.merge_range('G51:H51', "I/P converter Make / Model", cell_format1)

        worksheet.merge_range('G52:H52', "Solenoid Valve Make / Model", cell_format1)

        worksheet.merge_range('G53:H53', "Solenoid Action", cell_format1)

        worksheet.merge_range('G54:H54', "Volume Tank", cell_format1)

        worksheet.merge_range('G55:L55', "Testing, Certification, Cleaning, Painting", boldc)
        worksheet.merge_range('G42:L42', "Accessories & Tubings", boldc)

        worksheet.merge_range('G56:H56', "Testing-1", cell_format1)

        worksheet.merge_range('G57:H57', "Testing-2", cell_format1)

        worksheet.merge_range('G58:H58', "Testing-3", cell_format1)

        worksheet.merge_range('G59:H59', "Product Certification", cell_format1)

        worksheet.merge_range('G60:H60', "Assembly cleaning procedure", cell_format1)

        worksheet.merge_range('G61:H61', "Painting Specification", cell_format1)

        worksheet.merge_range('E13:F13', "Case2", boldc)

        worksheet.merge_range('E14:F14', "", cell_format)

        worksheet.merge_range('E15:F15', "", cell_format)

        worksheet.merge_range('E16:F16', "", cell_format)

        worksheet.merge_range('E17:F17', "", cell_format)

        worksheet.merge_range('E18:F18', "", cell_format)

        worksheet.merge_range('E19:F19', "", cell_format)

        worksheet.merge_range('E20:F20', "", cell_format)

        worksheet.merge_range('E21:F21', "", cell_format)

        worksheet.merge_range('E22:F22', "", cell_format)

        worksheet.merge_range('E23:F23', "", cell_format)

        worksheet.merge_range('E24:F24', "", cell_format)

        worksheet.merge_range('E25:F25', "", cell_format)

        worksheet.merge_range('E26:F26', "", cell_format)

        worksheet.merge_range('E27:F27', "", cell_format)

        # //worksheet.merge_range('E28:F28',"")

        worksheet.merge_range('I13:J13', "Case5", boldc)

        worksheet.merge_range('I14:J14', "", cell_format)

        worksheet.merge_range('I15:J15', "", cell_format)

        worksheet.merge_range('I16:J16', "", cell_format)

        worksheet.merge_range('I17:J17', "", cell_format)

        worksheet.merge_range('I18:J18', "", cell_format)

        worksheet.merge_range('I19:J19', "", cell_format)

        worksheet.merge_range('I20:J20', "", cell_format)

        worksheet.merge_range('I21:J21', "", cell_format)

        worksheet.merge_range('I22:J22', "", cell_format)

        worksheet.merge_range('I23:J23', "", cell_format)

        worksheet.merge_range('I24:J24', "", cell_format)

        worksheet.merge_range('I25:J25', "", cell_format)

        worksheet.merge_range('I26:J26', "", cell_format)

        worksheet.merge_range('I27:J27', "", cell_format)

        # //worksheet.merge_range('I28:J28',"")

        worksheet.merge_range('K13:L13', "Case6", boldc)

        worksheet.merge_range('K14:L14', "", cell_format)

        worksheet.merge_range('K15:L15', "", cell_format)

        worksheet.merge_range('K16:L16', "", cell_format)

        worksheet.merge_range('K17:L17', "", cell_format)

        worksheet.merge_range('K18:L18', "", cell_format)

        worksheet.merge_range('K19:L19', "", cell_format)

        worksheet.merge_range('K20:L20', "", cell_format)

        worksheet.merge_range('K21:L21', "", cell_format)

        worksheet.merge_range('K22:L22', "", cell_format)

        worksheet.merge_range('K23:L23', "", cell_format)

        worksheet.merge_range('K24:L24', "", cell_format)

        worksheet.merge_range('K25:L25', "", cell_format)

        worksheet.merge_range('K26:L26', "", cell_format)

        worksheet.merge_range('K27:L27', "", cell_format)

        worksheet.merge_range('D28:L28', "", cell_format)
        worksheet.merge_range('B28:C28', "Warnings!!", cell_format)

        # worksheet.merge_range('I30:J30', "", cell_format1)
        # worksheet.merge_range('K30:L30', "", br)

        # worksheet.merge_range('I31:J31', "", cell_format1)
        worksheet.merge_range('I31:L31', "", br)

        worksheet.merge_range('I32:J32', "", cell_format1)
        worksheet.merge_range('K32:L32', "", br)

        worksheet.merge_range('I33:J33', "", cell_format1)
        worksheet.merge_range('K33:L33', "", br)

        # worksheet.merge_range('I34:J34', "", cell_format1)
        worksheet.merge_range('I34:L34', "", br)

        worksheet.merge_range('I35:J35', "", cell_format1)
        worksheet.merge_range('K35:L35', "", br)

        # worksheet.merge_range('I36:J36', "", cell_format1)
        worksheet.merge_range('I36:L36', "", br)

        # worksheet.merge_range('I37:J37', "", cell_format1)
        worksheet.merge_range('I37:L37', "", br)

        # worksheet.merge_range('I38:J38', "", cell_format1)
        worksheet.merge_range('I38:L38', "", br)

        worksheet.merge_range('I39:J39', "", cell_format1)
        worksheet.merge_range('K39:L39', "", br)

        # worksheet.merge_range('I40:J40', "", cell_format1)
        worksheet.merge_range('I40:L40', "", br)

        # worksheet.merge_range('I41:J41', "", cell_format1)
        worksheet.merge_range('K41:L41', "", cell_format1)

        # worksheet.merge_range('I42:J42', "", cell_format1)
        # worksheet.merge_range('K42:L42', "", br)

        worksheet.merge_range('I43:J43', "", cell_format1)
        worksheet.merge_range('K43:L43', "", br)

        # worksheet.merge_range('I44:J44', "", cell_format1)
        worksheet.merge_range('I44:L44', "", br)

        worksheet.merge_range('I45:J45', "", cell_format1)
        worksheet.merge_range('K45:L45', "", br)

        # worksheet.merge_range('I46:J46', "", cell_format1)
        worksheet.merge_range('I46:L46', "", br)

        worksheet.merge_range('I47:J47', "", cell_format1)
        worksheet.merge_range('K47:L47', "", br)

        # worksheet.merge_range('I48:J48', "", cell_format1)
        worksheet.merge_range('I48:L48', "", br)

        worksheet.merge_range('I49:J49', "", cell_format1)
        worksheet.merge_range('K49:L49', "", br)

        # worksheet.merge_range('I50:J50', "", cell_format1)
        worksheet.merge_range('I50:L50', "", br)

        worksheet.merge_range('I51:J51', "", cell_format1)
        worksheet.merge_range('K51:L51', "", br)

        worksheet.merge_range('I52:J52', "", cell_format1)
        worksheet.merge_range('K52:L52', "", br)

        # worksheet.merge_range('I53:J53', "", cell_format1)
        worksheet.merge_range('I53:L53', "", br)

        # worksheet.merge_range('I54:J54', "", cell_format1)
        worksheet.merge_range('I54:L54', "", br)

        # worksheet.merge_range('I56:J56', "", cell_format1)
        worksheet.merge_range('I56:L56', "", br)

        # worksheet.merge_range('I57:J57', "", cell_format1)
        worksheet.merge_range('I57:L57', "", br)

        # worksheet.merge_range('I58:J58', "", cell_format1)
        worksheet.merge_range('I58:L58', "", br)

        # worksheet.merge_range('I59:J59', "", cell_format1)
        worksheet.merge_range('I59:L59', "", br)

        # worksheet.merge_range('I60:J60', "", cell_format1)
        worksheet.merge_range('I60:L60', "", br)

        # worksheet.merge_range('I61:J61', "", cell_format1)
        worksheet.merge_range('I61:L61', "", br)

        worksheet.merge_range('A73:D73', "")
        worksheet.merge_range('J73:L73', "QMS/AE/002", f1)

        worksheet.merge_range('C1:H1', "")
        worksheet.merge_range('B62:I62', "Notes", boldc)
        worksheet.merge_range('B63:I63', "N1- MPI-Body/Bnt Castings/Forgings to ASME B16.34 at Foundry/Forge",
                              cell_format)
        worksheet.merge_range('B64:I64', "", cell_format)
        worksheet.merge_range('B65:I65', "", cell_format)
        worksheet.merge_range('B66:I66', "", cell_format)
        worksheet.merge_range('B67:I67', "", cell_format)
        worksheet.merge_range('B68:I68', "", cell_format)
        worksheet.merge_range('B69:I69', "", cell_format)
        worksheet.merge_range('B70:I70', "", cell_format)
        worksheet.merge_range('B71:I71', "", cell_format)
        worksheet.merge_range('B72:I72', "", cell_format)
        worksheet.merge_range('J62:L62', "Revison Control", boldc)
        worksheet.merge_range('A29:L29', "")

        worksheet.merge_range('C4:F4', "", cell_format)
        worksheet.merge_range('C5:F5', "", cell_format)
        worksheet.merge_range('C6:F6', "", cell_format)
        worksheet.merge_range('C7:F7', "", cell_format)
        worksheet.merge_range('C8:F8', "", cell_format)
        worksheet.merge_range('C9:F9', "", cell_format)
        worksheet.merge_range('H4:L4', "", cell_format)
        worksheet.merge_range('H5:L5', "", cell_format)
        worksheet.merge_range('H6:L6', "", cell_format)
        worksheet.merge_range('H7:L7', "", cell_format)
        worksheet.merge_range('H8:L8', "", cell_format)
        worksheet.merge_range('H9:L9', "", cell_format)

        # add data
        worksheet.write('C4', str(case_data[i][0][-1]), cell_format1)
        worksheet.write('C11', str(case_data[i][0][16]), f2)
        worksheet.write('H4', str(case_data[i][0][22]), cell_format1)
        worksheet.write('H5', str(case_data[i][0][23]), cell_format1)
        worksheet.write('H7', str(case_data[i][0][14]), cell_format1)
        worksheet.write('H9', str(case_data[i][0][15]), cell_format1)
        worksheet.write('C31', str(case_data[i][0][18]), cell_format1)
        worksheet.write('C32', str(case_data[i][0][19]), cell_format1)

        column_dict_tuple = [('D', 0), ('E', 1), ('G', 2), ('H', 3), ('I', 4), ('K', 5)]
        len_cases = len(case_data[i])
        if len_cases > 6:
            len_cases = 6
        for k in column_dict_tuple[:len_cases]:
            for j in range(14):
                worksheet.write(f'{k[0]}{j + 14}', case_data[i][k[1]][j], cell_format)
        for j in range(14):
            worksheet.write(f'C{j + 14}', units[i][j], cell_format)
        worksheet.write(f'D31', units[i][-1], cell_format1)
        worksheet.write(f'D32', units[i][-2], cell_format1)

        # other[i] values input
        worksheet.write(f'H6', other[i][0], cell_format1)
        worksheet.write(f'H8', str(other[i][1]), cell_format1)
        worksheet.write(f'C5', str(other[i][2]), cell_format)
        worksheet.write(f'I11', other[i][3], f2)
        worksheet.write(f'J11', other[i][4], f2)
        worksheet.write(f'I12', other[i][5], f2)
        worksheet.write(f'C38', other[i][6], f2)
        worksheet.write(f'D38', other[i][7], cell_format1)
        worksheet.write(f'E38', other[i][8], f2)
        worksheet.write(f'C40', other[i][9], cell_format1)
        worksheet.write(f'C44', other[i][10], cell_format1)
        worksheet.write(f'C47', other[i][11], cell_format1)
        worksheet.write(f'C48', other[i][12], cell_format1)
        worksheet.write(f'C50', other[i][13], cell_format1)
        worksheet.write(f'C53', other[i][14], cell_format1)
        worksheet.write(f'C56', other[i][15], cell_format1)
        worksheet.write(f'C58', other[i][16], cell_format1)
        worksheet.write(f'C57', other[i][17], cell_format1)
        worksheet.write(f'C59', other[i][18], cell_format1)
        worksheet.write(f'C41', other[i][19], cell_format1)
        worksheet.write(f'C42', other[i][20], cell_format1)
        worksheet.write(f'C39', other[i][21], cell_format1)

        # other data
        worksheet.write(f'C34', case_data[i][0][1], cell_format1)
        worksheet.write(f'C35', case_data[i][0][3], cell_format1)
        worksheet.write(f'C37', other[i][22], cell_format1)
        worksheet.write(f'C45', other[i][23], cell_format1)
        worksheet.write(f'C46', other[i][24], cell_format1)
        worksheet.write(f'C49', other[i][25], cell_format1)
        worksheet.write(f'C54', other[i][26], cell_format1)
        worksheet.write(f'C55', other[i][27], cell_format1)

        # Actuator Data
        worksheet.write(f'I31', act_['act_type'], cell_format1)
        worksheet.write(f'I32', f'/{act_["Travel"]}', cell_format1)
        worksheet.write(f'I33', f'{act_["act_size"]}', cell_format1)
        worksheet.write(f'I34', f'{act_["fail_action"]}', cell_format1)
        worksheet.write(f'I31', act_['act_type'], cell_format1)
        worksheet.write(f'I35', f'{act_["max_air_supply"]}/{act_["set_pressure"]}', cell_format1)
        worksheet.write(f'I36', act_['orientation'], cell_format1)
        worksheet.write(f'I37', act_['handwheel'], cell_format1)

        # Accessories data
        worksheet.write(f'I43', other[i][28][0], cell_format1)
        worksheet.write(f'K43', other[i][28][1], cell_format1)
        worksheet.write(f'I44', other[i][28][2], cell_format1)
        worksheet.write(f'I45', other[i][28][3], cell_format1)
        worksheet.write(f'K45', other[i][28][4], cell_format1)
        worksheet.write(f'I46', other[i][28][5], cell_format1)
        worksheet.write(f'I47', other[i][28][6], cell_format1)
        worksheet.write(f'K47', other[i][28][7], cell_format1)
        worksheet.write(f'I48', other[i][28][8], cell_format1)
        worksheet.write(f'I49', other[i][28][9], cell_format1)
        worksheet.write(f'I50', other[i][28][10], cell_format1)
        worksheet.write(f'I51', other[i][28][11], cell_format1)
        worksheet.write(f'K51', other[i][28][12], cell_format1)
        worksheet.write(f'I52', other[i][28][13], cell_format1)
        worksheet.write(f'K52', other[i][28][14], cell_format1)
        worksheet.write(f'I53', other[i][28][15], cell_format1)
        worksheet.write(f'I44', other[i][28][16], cell_format1)

    workbook.close()


act_dict = {'v_type': 0, 'trim_type': 0, 'Balancing': 0, 'fl_direction': 'over', 'v_size': 0, 'v_size_unit': 'mm',
            'Seat_Dia': 0,
            'seat_dia_unit': 'mm', 'unbalance_area': 0, 'unbalance_area_unit': 'mm',
            'Stem_size': 0, 'Stem_size_unit': 'mm', 'Travel': 0, 'travel_unit': 'mm', 'Packing_Friction': 0,
            'packing_friction_unit': 'mm', 'Seat_Load_Factor': 0, 'Additional_Factor': 0, 'P1': 0, 'p1_unit': 'mm',
            'P2': 0, 'p2_unit': 'mm',
            'delP_Shutoff': 0, 'delP_Shutoff_unit': 'mm', 'unbal_force': 0, 'Kn': 0, 'delP_flowing': 0, 'act_type': 0,
            'fail_action': 0, 'act_size': 0, 'act_size_unit': 'mm', 'act_travel': 0, 'act_travel_unit': 'mm',
            'eff_area': 0, 'eff_area_unit': 'mm',
            'sMin': 0, 'sMax': 0, 'spring_rate': 0, 'spring_windup': 0, 'max_spring_load': 0,
            'max_air_supply': 0,
            'set_pressure': 0, 'set_pressure_unit': 'mm', 'act_thrust_down': 0, 'act_thrust_up': 0, 'friction_band': 0,
            'req_handWheel_thrust': 0, 'max_thrust': 0,
            'v_thrust_close': 0, 'v_thrust_open': 0, 'seat_load': 0
            }

proj_details = {'customer': '', 'project': 1, 'quote': '', 'wo': '', 'sNo': '', 'tagNo': '', 'qty': 1, 'item_no': 1}


def createActSpecSheet(act_data, proj_data):
    current_datetime = datetime.today().date().timetuple()
    str_current_datetime = str(current_datetime)
    a__ = datetime.now()
    a_ = a__.strftime("%a, %d %b %Y %H-%M-%S")

    workbook = xlsxwriter.Workbook('act_specsheet.xlsx')
    worksheet = workbook.add_worksheet()

    worksheet.set_paper(9)
    worksheet.fit_to_pages(1, 1)
    worksheet.print_area('A1:I62')
    worksheet.set_margins(0.6, 0.52, 0.6, 0.8)
    worksheet.set_row(2, 18)

    bold = workbook.add_format(
        {'bold': True, 'bottom': 1, 'top': 1, 'right': 1, 'left': 1, 'border_color': '#B2B2B2', 'bg_color': '#EFF5F5'})
    bold1 = workbook.add_format(
        {'bold': True, 'bottom': 1, 'top': 1, 'left': 1, 'border_color': '#B2B2B2', 'bg_color': '#EFF5F5'})
    boldc = workbook.add_format(
        {'align': 'center', 'bold': True, 'bottom': 1, 'top': 1, 'right': 1, 'left': 1, 'border_color': '#B2B2B2',
         'bg_color': '#EFF5F5'})
    br = workbook.add_format({'bottom': 1, 'top': 1, 'right': 1, 'border_color': '#B2B2B2'})
    h1 = workbook.add_format({'bold': True, 'font_size': 12, 'align': 'center', 'font': 'Arial'})
    h2 = workbook.add_format({'bold': 0, 'font_size': 10, 'font': 'Arial'})
    h3 = workbook.add_format({'bold': 0, 'font_size': 9, 'font': 'Arial'})
    f1 = workbook.add_format({'bold': 0, 'font_size': 9, 'font': 'Arial', 'align': 'right'})

    cell_format1 = workbook.add_format({'bottom': 1, 'top': 1, 'border_color': '#B2B2B2'})
    cell_formatR = workbook.add_format({'align': 'Right', 'bottom': 1, 'top': 1, 'border_color': '#B2B2B2'})
    cell_format = workbook.add_format(
        {'bold': 0, 'font_color': 'black', 'font': 'Arial', 'font_size': 9, 'bottom': 1, 'top': 1, 'right': 1,
         'left': 1,
         'border_color': '#B2B2B2'})

    cell_format2 = workbook.add_format(
        {'bold': 0, 'align': 'center', 'font_color': 'black', 'font': 'Arial', 'font_size': 9, 'bottom': 1, 'top': 1,
         'right': 1, 'left': 1, 'border_color': '#B2B2B2'})

    column_width = [{'name': 'A1:A73', 'size': 5}, {'name': 'B1:B73', 'size': 24}, {'name': 'C1:C73', 'size': 10},
                    {'name': 'D1:D73', 'size': 13},
                    {'name': 'E1:E73', 'size': 5}, {'name': 'F1:F73', 'size': 12}, {'name': 'G1:G73', 'size': 12},
                    {'name': 'H1:H73', 'size': 10},
                    {'name': 'I1:I73', 'size': 13}, {'name': 'J1:J73', 'size': 6}, {'name': 'K1:K73', 'size': 5},
                    {'name': 'L1:L73', 'size': 8}]

    for i in column_width:
        worksheet.set_column(i['name'], i['size'])

    worksheet.write('A1', 'Flow Control Commune Pvt Ltd', h2)
    worksheet.write('A2', 'Chennai, India')
    worksheet.write('A3', '')
    worksheet.merge_range('A4:B4', "Customer", cell_format)
    worksheet.merge_range('A5:B5', "Project", cell_format)
    worksheet.merge_range('A6:B6', "End User", cell_format)
    worksheet.merge_range('A7:B7', "RFQ No", cell_format)
    worksheet.merge_range('A8:B8', "PO No", cell_format)
    worksheet.merge_range('A9:B9', "P & ID Ref  /  Line No", cell_format)
    worksheet.write('A10', '')
    worksheet.write('A11', '', f2)
    worksheet.write('A12', '', f2)
    worksheet.write('A13', 'AA', boldc)
    worksheet.write('A14', '1', cell_format2)
    worksheet.write('A15', '2', cell_format2)
    worksheet.write('A16', '3', cell_format2)
    worksheet.write('A17', '4', cell_format2)
    worksheet.write('A18', '5', cell_format2)
    worksheet.write('A19', '6', cell_format2)
    worksheet.write('A20', '7', cell_format2)
    worksheet.write('A21', '8', cell_format2)
    worksheet.write('A22', '9', cell_format2)
    worksheet.write('A23', '10', cell_format2)
    worksheet.write('A24', '11', cell_format2)
    worksheet.write('A25', '12', cell_format2)
    worksheet.write('A26', '13', cell_format2)
    worksheet.write('A27', '14', cell_format2)
    worksheet.write('A28', '15', cell_format2)
    worksheet.write('A29', '16', cell_format2)
    worksheet.write('A30', '17', bold)
    worksheet.write('A31', '18', cell_format2)
    worksheet.write('A32', 'BB', bold)
    worksheet.write('A33', '19', cell_format2)
    worksheet.write('A34', '20', cell_format2)
    worksheet.write('A35', '21', cell_format2)
    worksheet.write('A37', '', )
    worksheet.write('A38', '', )
    worksheet.write('A39', 'DD', bold)
    worksheet.write('A40', '', cell_format2)
    worksheet.write('A41', '', cell_format2)
    worksheet.write('A42', '', cell_format2)
    worksheet.write('A43', '', cell_format2)
    worksheet.write('A44', '', cell_format2)
    worksheet.write('A45', '', cell_format2)
    worksheet.write('A46', '', cell_format2)
    worksheet.write('A47', '', cell_format2)
    worksheet.write('A48', '', cell_format2)
    worksheet.write('A49', '', )
    worksheet.write('A50', '', )
    worksheet.write('A51', '', )
    worksheet.write('A52', '', )
    worksheet.write('A53', '', )
    worksheet.write('A54', '', )
    worksheet.write('A62', 'FLOW CONTROL COMMUNE PVT LTD', )

    worksheet.write('B2', '')
    worksheet.write('B3', '')
    worksheet.write('B10', '')
    worksheet.write('B11', '')
    worksheet.write('B12', '')
    worksheet.write('B13', 'Valve Data', bold)
    worksheet.write('B14', 'Valve Type', cell_format)
    worksheet.write('B15', 'Trim Type', cell_format)
    worksheet.write('B16', 'Balancing', cell_format)
    worksheet.write('B17', 'Flow Direction', cell_format)
    worksheet.write('B18', 'Valve Size', cell_format)
    worksheet.write('B19', 'Seat Diameter', cell_format)
    worksheet.write('B20', 'Unbalanced Area', cell_format)
    worksheet.write('B21', 'Valve Stem Size ', cell_format)
    worksheet.write('B22', 'Valve Travel', cell_format)
    worksheet.write('B23', 'Packing Friction', cell_format)
    worksheet.write('B24', 'Seat Load Factor ', cell_format)
    worksheet.write('B25', 'Additional Friction   ', cell_format)
    worksheet.write('B26', 'P1 Max  ', cell_format)
    worksheet.write('B27', 'P2 Min', cell_format)

    worksheet.write('B28', 'ΔP Shutoff', cell_format1)
    worksheet.write('B29', 'Unbalance Force @Open', cell_format1)
    worksheet.write('B30', 'Fluid Negative Gradient', boldc)
    worksheet.write('B31', 'ΔP Flowing', cell_format1)
    worksheet.write('B32', 'Valve Forces', bold)
    worksheet.write('B33', 'Valve Thrust (close)', cell_format1)
    worksheet.write('B34', 'Valve Thrust (Open)', cell_format1)
    worksheet.write('B35', 'Seat Load Force', cell_format1)
    worksheet.write('B49', '', )
    worksheet.write('B50', '', )
    worksheet.write('B51', '', )
    worksheet.write('B53', '', )
    worksheet.write('B54', '', )

    worksheet.write('C2', '')
    worksheet.write('C3', '')
    worksheet.write('C10', '')
    worksheet.write('C11', '')
    worksheet.write('C12', '')
    worksheet.write('C13', 'Units', bold)
    worksheet.write('C14', '', cell_format)
    worksheet.write('C15', '', cell_format)
    worksheet.write('C16', '', cell_format)
    worksheet.write('C17', '', cell_format)
    worksheet.write('C18', '', cell_format)
    worksheet.write('C19', '', cell_format)
    worksheet.write('C20', '', cell_format)
    worksheet.write('C21', '', cell_format)
    worksheet.write('C22', '', cell_format)
    worksheet.write('C23', '', cell_format)
    worksheet.write('C24', '', cell_format)
    worksheet.write('C25', '', cell_format)
    worksheet.write('C26', '', cell_format)
    worksheet.write('C27', '', cell_format)
    worksheet.write('C28', '', cell_format)
    worksheet.write('C29', '', cell_format)
    worksheet.write('C30', '', cell_format)
    worksheet.write('C31', '', cell_format)
    worksheet.write('C32', 'Units', bold)
    worksheet.write('C33', '', cell_format)
    # worksheet.write('C34', '', cell_format)
    # worksheet.write('C35', '', cell_format)
    worksheet.write('C49', '', )
    worksheet.write('C50', '', )
    worksheet.write('C51', '', )
    worksheet.write('C52', '', )
    worksheet.write('C53', '', )
    worksheet.write('C54', '', )

    worksheet.write('D2', '')
    worksheet.write('D3', '')
    worksheet.write('D10', '')
    worksheet.write('D11', '')
    worksheet.write('D12', '')
    worksheet.write('D13', 'Values', bold)
    worksheet.write('D14', '', cell_format)
    worksheet.write('D15', '', cell_format)
    worksheet.write('D16', '', cell_format)
    worksheet.write('D17', '', cell_format)
    worksheet.write('D18', '', cell_format)
    worksheet.write('D19', '', cell_format)
    worksheet.write('D20', '', cell_format)
    worksheet.write('D21', '', cell_format)
    worksheet.write('D22', '', cell_format)
    worksheet.write('D23', '', cell_format)
    worksheet.write('D24', '', cell_format)
    worksheet.write('D25', '', cell_format)
    worksheet.write('D26', '', cell_format)
    worksheet.write('D27', '', cell_format)
    worksheet.write('D28', '', cell_format)
    worksheet.write('D29', '', cell_format)
    worksheet.write('D30', '', cell_format)
    worksheet.write('D31', '', cell_format)
    worksheet.write('D32', 'Values', bold)
    worksheet.write('D33', '', br)
    worksheet.write('D34', '', br)
    worksheet.write('D35', '', br)
    worksheet.write('D49', '', )
    worksheet.write('D50', '', )
    worksheet.write('D51', '', )
    worksheet.write('D52', '', )
    worksheet.write('D53', '', )

    worksheet.write('E2', '')
    worksheet.write('E3', '')
    worksheet.write('E10', '')
    worksheet.write('E11', '')
    worksheet.write('E12', '')
    worksheet.write('E13', 'CC', boldc)
    worksheet.write('E14', '22', cell_format2)
    worksheet.write('E15', '23', cell_format2)
    worksheet.write('E16', '24', cell_format2)
    worksheet.write('E17', '25', cell_format2)
    worksheet.write('E18', '26', cell_format2)
    worksheet.write('E19', '27', cell_format2)
    worksheet.write('E20', '28', cell_format2)
    worksheet.write('E21', '29', cell_format2)
    worksheet.write('E22', '30', cell_format2)
    worksheet.write('E23', '31', cell_format2)
    worksheet.write('E24', '32', cell_format2)
    worksheet.write('E25', '33', cell_format2)
    worksheet.write('E26', '34', cell_format2)
    worksheet.write('E27', '35', cell_format2)
    worksheet.write('E28', '36', cell_format2)
    worksheet.write('E29', '37', cell_format2)
    worksheet.write('E30', '38', cell_format2)
    worksheet.write('E31', '', cell_format1)
    worksheet.write('E32', '', cell_format1)
    worksheet.write('E33', '', cell_format1)
    worksheet.write('E34', '', cell_format1)
    worksheet.write('E35', '', cell_format1)
    worksheet.write('E49', '', )
    worksheet.write('E50', '', )
    worksheet.write('E51', '', )
    worksheet.write('E52', '', )
    worksheet.write('E53', '', )

    worksheet.write('F2', '')
    worksheet.write('F3', '')
    worksheet.write('F4', 'Quote No', cell_format)
    worksheet.write('F5', 'FCC W/O No', cell_format)
    worksheet.write('F6', 'Serial No', cell_format)
    worksheet.write('F7', 'Tag No', cell_format)
    worksheet.write('F8', 'Qty', cell_format)
    worksheet.write('F9', 'Item No.', cell_format)
    worksheet.write('F10', '')
    worksheet.write('F11', '')
    worksheet.write('F12', '')
    worksheet.write('F49', '', )
    worksheet.write('F50', '', )
    worksheet.write('F51', '', )
    worksheet.write('F52', '', )
    worksheet.write('F53', '', )

    worksheet.write('G2', '', )
    worksheet.write('G3', '', )
    worksheet.write('G4', '', cell_format)
    worksheet.write('G5', '', cell_format)
    worksheet.write('G6', '', cell_format)
    worksheet.write('G7', '', cell_format)
    worksheet.write('G8', '', cell_format)
    worksheet.write('G9', '', cell_format)
    worksheet.write('G10', '', )
    worksheet.write('G11', '', f1)
    worksheet.write('G12', '', f1)
    worksheet.write('G49', '', )
    worksheet.write('G50', '', )
    worksheet.write('G51', '', )
    worksheet.write('G52', '', )
    worksheet.write('G53', '', )

    worksheet.insert_image('H1', 'Logo.png', {'x_scale': 0.7, 'y_scale': 0.6})
    worksheet.write('H2', '', )
    worksheet.write('H3', '', )
    worksheet.write('H4', '', cell_format)
    worksheet.write('H5', '', cell_format)
    worksheet.write('H6', '', cell_format)
    worksheet.write('H7', '', cell_format)
    worksheet.write('H8', '', cell_format)
    worksheet.write('H9', '', cell_format)
    worksheet.write('H10', '', )
    worksheet.write('H11', '', )
    worksheet.write('H12', '', )
    worksheet.write('H13', 'Units', bold)
    worksheet.write('H14', '', cell_format)
    worksheet.write('H15', '', cell_format)
    worksheet.write('H16', '', cell_format)
    worksheet.write('H17', '', cell_format)
    worksheet.write('H18', '', cell_format)
    worksheet.write('H19', '', cell_format)
    worksheet.write('H20', '', cell_format)
    worksheet.write('H21', '', cell_format)
    worksheet.write('H22', '', cell_format)
    worksheet.write('H23', '', cell_format)
    worksheet.write('H24', '', cell_format)
    worksheet.write('H25', '', cell_format)
    worksheet.write('H26', '', cell_format)
    worksheet.write('H27', '', cell_format)
    worksheet.write('H28', '', cell_format)
    worksheet.write('H29', '', cell_format)
    worksheet.write('H30', '', cell_format)
    worksheet.write('H31', '', cell_format)
    worksheet.write('H32', '', cell_format)
    worksheet.write('H33', '', cell_format)
    worksheet.write('H34', '', cell_format)
    worksheet.write('H35', '', cell_format)
    worksheet.write('H49', '', )
    worksheet.write('H50', '', )
    worksheet.write('H51', '', )
    worksheet.write('H52', '', )
    worksheet.write('H53', '', )
    worksheet.write('H54', '', )

    worksheet.write('H49', '', )
    worksheet.write('H50', '', )
    worksheet.write('H51', '', )
    worksheet.write('H52', '', )
    worksheet.write('H53', '', )

    worksheet.write('I2', '', )
    worksheet.write('I3', '', )
    worksheet.write('I4', '', cell_format)
    worksheet.write('I5', '', cell_format)
    worksheet.write('I6', '', cell_format)
    worksheet.write('I7', '', cell_format)
    worksheet.write('I8', '', cell_format)
    worksheet.write('I9', '', cell_format)
    worksheet.write('I10', '', )
    worksheet.write('I11', '', )
    worksheet.write('I12', '', )
    worksheet.write('I13', 'Values', bold)
    worksheet.write('I14', '', cell_format)
    worksheet.write('I15', '', cell_format)
    worksheet.write('I16', '', cell_format)
    worksheet.write('I17', '', cell_format)
    worksheet.write('I18', '', cell_format)
    worksheet.write('I19', '', cell_format)
    worksheet.write('I20', '', cell_format)
    worksheet.write('I21', '', cell_format)
    worksheet.write('I22', '', cell_format)
    worksheet.write('I23', '', cell_format)
    worksheet.write('I24', '', cell_format)
    worksheet.write('I25', '', cell_format)
    worksheet.write('I26', '', cell_format)
    worksheet.write('I27', '', cell_format)
    worksheet.write('I28', '', cell_format)
    worksheet.write('I29', '', cell_format)
    worksheet.write('I30', '', cell_format)
    worksheet.write('I31', '', cell_format)
    worksheet.write('I32', '', cell_format)
    worksheet.write('I33', '', cell_format)
    worksheet.write('I34', '', cell_format)
    worksheet.write('I35', '', cell_format)
    # worksheet.write('I36', '', cell_format)

    worksheet.write('I39', 'Revised Date', bold)
    worksheet.write('I40', '', cell_format2)
    worksheet.write('I41', '', cell_format1)
    worksheet.write('I42', '', cell_format2)
    worksheet.write('I43', '', cell_format2)
    worksheet.write('I44', '', cell_format2)
    worksheet.write('I45', '', cell_format2)
    worksheet.write('I46', '', cell_format2)
    worksheet.write('I47', '', cell_format2)
    worksheet.write('I48', '', cell_format2)
    worksheet.write('I49', '', )
    worksheet.write('I50', '', )
    worksheet.write('I51', '', )
    worksheet.write('I52', '', )
    worksheet.write('I53', '', )

    worksheet.merge_range('H62:I62', "QMS/AE/002, ISSUE 1", f1)
    worksheet.merge_range('G4:I4', "", br)
    worksheet.merge_range('G5:I5', "", br)
    worksheet.merge_range('G6:I6', "", br)
    worksheet.merge_range('G7:I7', "", br)
    worksheet.merge_range('G8:I8', "", br)
    worksheet.merge_range('G9:I9', "", br)
    worksheet.merge_range('F13:G13', 'Actuator Details', boldc)
    worksheet.merge_range('F14:G14', 'Actuator Type', cell_format)
    worksheet.merge_range('F15:G15', 'Air Fail Action', cell_format)
    worksheet.merge_range('F16:G16', 'Actuator Size  ', cell_format)
    worksheet.merge_range('F17:G17', 'Actuator Travel', cell_format)
    worksheet.merge_range('F18:G18', 'Diaphragm Effective Area', cell_format)
    worksheet.merge_range('F19:G19', 'Lower Bench Set', cell_format)
    worksheet.merge_range('F20:G20', 'Upper Bench Set ', cell_format)
    worksheet.merge_range('F21:G21', 'Spring Rate ', cell_format)
    worksheet.merge_range('F22:G22', 'Spring Windup ', cell_format)
    worksheet.merge_range('F23:G23', 'Max Spring Load', cell_format)
    worksheet.merge_range('F24:G24', 'Max Air Supply', cell_format)
    worksheet.merge_range('F25:G25', 'Set Pressure', cell_format)
    worksheet.merge_range('F26:G26', 'Actuator Thrust Down ', cell_format)
    worksheet.merge_range('F27:G27', 'Actuator Thrust Up', cell_format)
    worksheet.merge_range('F28:G28', 'Friction Band', cell_format)
    worksheet.merge_range('F29:G29', 'Req. HandWheel Thrust', cell_format)
    worksheet.merge_range('F30:G30', 'Max Top/Side Mount HW Thrust', boldc)
    worksheet.merge_range('F31:G31', '', cell_format)
    worksheet.merge_range('F32:G32', '', cell_format)
    worksheet.merge_range('F33:G33', '', cell_format)
    worksheet.merge_range('F34:G34', '', cell_format)
    worksheet.merge_range('F35:G35', '', cell_format)
    # worksheet.merge_range('F36:G36', '', cell_format)

    worksheet.merge_range('C4:E4', '', cell_format)
    worksheet.merge_range('C5:E5', '', cell_format)
    worksheet.merge_range('C6:E6', '', cell_format)
    worksheet.merge_range('C7:E7', '', cell_format)
    worksheet.merge_range('C8:E8', '', cell_format)
    worksheet.merge_range('C9:E9', '', cell_format)

    worksheet.merge_range('B39:H39', 'Comments', bold)
    worksheet.merge_range('B40:H40', '', cell_format)
    worksheet.merge_range('B41:H41', '', cell_format)
    worksheet.merge_range('B42:H42', '', cell_format)
    worksheet.merge_range('B43:H43', '', cell_format)
    worksheet.merge_range('B44:H44', '', cell_format)
    worksheet.merge_range('B45:H45', '', cell_format)
    worksheet.merge_range('B46:H46', '', cell_format)
    worksheet.merge_range('B47:H47', '', cell_format)
    worksheet.merge_range('B48:H48', '', cell_format)

    worksheet.merge_range('C1:G1', "Actuator Sizing Calculation Sheet", h1)

    # Add data - proj details
    worksheet.write('C4', str(proj_data['customer']), cell_format)
    worksheet.write('C5', str(proj_data['project']), cell_format)
    worksheet.write('G4', str(proj_data['quote']), cell_format)
    worksheet.write('G5', str(proj_data['wo']), cell_format)
    worksheet.write('G6', str(proj_data['sNo']), cell_format)
    worksheet.write('G7', str(proj_data['tagNo']), cell_format)
    worksheet.write('G8', str(proj_data['qty']), cell_format)
    worksheet.write('G9', str(proj_data['item_no']), cell_format)

    # Add data - actuator Data
    worksheet.write('D14', str(act_data['v_type']), cell_format)
    worksheet.write('D15', str(act_data['trim_type']), cell_format)
    worksheet.write('D16', str(act_data['Balancing']), cell_format)
    worksheet.write('D17', str(act_data['fl_direction']), cell_format)
    worksheet.write('D18', str(act_data['v_size']), cell_format)
    worksheet.write('C18', str(act_data['v_size_unit']), cell_format)
    worksheet.write('D19', str(act_data['Seat_Dia']), cell_format)
    worksheet.write('C19', str(act_data['seat_dia_unit']), cell_format)
    worksheet.write('D20', str(act_data['unbalance_area']), cell_format)
    worksheet.write('C20', str(act_data['unbalance_area_unit']), cell_format)
    worksheet.write('D21', str(act_data['Stem_size']), cell_format)
    worksheet.write('C21', str(act_data['Stem_size_unit']), cell_format)
    worksheet.write('D22', str(act_data['Travel']), cell_format)
    worksheet.write('C22', str(act_data['travel_unit']), cell_format)
    worksheet.write('D23', str(act_data['Packing_Friction']), cell_format)
    worksheet.write('C23', str(act_data['packing_friction_unit']), cell_format)
    worksheet.write('D24', str(act_data['Seat_Load_Factor']), cell_format)
    worksheet.write('D25', str(act_data['Additional_Factor']), cell_format)
    worksheet.write('D26', str(act_data['P1']), cell_format)
    worksheet.write('C26', str(act_data['p1_unit']), cell_format)
    worksheet.write('D27', str(act_data['P2']), cell_format)
    worksheet.write('C27', str(act_data['p2_unit']), cell_format)
    worksheet.write('D28', str(act_data['delP_Shutoff']), cell_format)
    worksheet.write('C28', str(act_data['delP_Shutoff_unit']), cell_format)
    worksheet.write('D29', str(act_data['unbal_force']), cell_format)
    worksheet.write('D30', str(act_data['Kn']), cell_format)
    worksheet.write('D31', str(act_data['delP_flowing']), cell_format)

    worksheet.write('I14', str(act_data['act_type']), cell_format)
    worksheet.write('I15', str(act_data['fail_action']), cell_format)
    worksheet.write('I16', str(act_data['act_size']), cell_format)
    worksheet.write('H16', str(act_data['act_size_unit']), cell_format)
    worksheet.write('I17', str(act_data['act_travel']), cell_format)
    worksheet.write('H17', str(act_data['act_travel_unit']), cell_format)
    worksheet.write('I18', str(act_data['eff_area']), cell_format)
    worksheet.write('H18', str(act_data['eff_area_unit']), cell_format)
    worksheet.write('I19', str(act_data['sMin']), cell_format)
    worksheet.write('I20', str(act_data['sMax']), cell_format)
    worksheet.write('I21', str(act_data['spring_rate']), cell_format)
    worksheet.write('I22', str(act_data['spring_windup']), cell_format)
    worksheet.write('I23', str(act_data['max_spring_load']), cell_format)
    worksheet.write('I24', str(act_data['max_air_supply']), cell_format)
    worksheet.write('I25', str(act_data['set_pressure']), cell_format)
    worksheet.write('H25', str(act_data['set_pressure_unit']), cell_format)
    worksheet.write('I26', str(act_data['act_thrust_down']), cell_format)
    worksheet.write('I27', str(act_data['act_thrust_up']), cell_format)
    worksheet.write('I28', str(act_data['friction_band']), cell_format)
    worksheet.write('I29', str(act_data['req_handWheel_thrust']), cell_format)
    worksheet.write('I30', str(act_data['max_thrust']), cell_format)

    worksheet.write('D33', str(act_data['v_thrust_close']), cell_format)
    worksheet.write('D34', str(act_data['v_thrust_open']), cell_format)
    worksheet.write('D35', str(act_data['seat_load']), cell_format)

    workbook.close()
