import xlsxwriter
from datetime import datetime

current_datetime = datetime.today().date().timetuple()
str_current_datetime = str(current_datetime)
a__ = datetime.now()
a_ = a__.strftime("%a, %d %b %Y %H-%M-%S")

workbook = xlsxwriter.Workbook(f'C:\\Users\\FCC\\Desktop\\{a_}.xlsx')
worksheet = workbook.add_worksheet()



worksheet.set_paper(9)
worksheet.fit_to_pages(2, 1)
worksheet.print_area('A2:M72')
worksheet.set_margins(0.36, 0.2, 0.4, 0.01)
worksheet.set_header(margin=0.2)
worksheet.set_footer(margin=0.28)


bold = workbook.add_format(
    {'bold': True, 'bottom': 1, 'top': 1, 'right': 1, 'left': 1, 'font': 'Arial', 'font_size': 9, 'border': 7, 'bg_color': '#EFF5F5'})
bold1 = workbook.add_format(
    {'bold': True, 'bottom': 1, 'top': 1, 'left': 1, 'border': 7, 'bg_color': '#EFF5F5'})
boldc = workbook.add_format(
    {'align': 'center', 'bold': True, 'bottom': 1, 'top': 1, 'right': 1, 'left': 1,'font': 'Arial', 'font_size': 9, 'border': 7,
     'bg_color': '#EFF5F5'})
br = workbook.add_format({'bottom': 1, 'top': 1, 'right': 1, 'border': 7})
h1 = workbook.add_format({'bold': True, 'font_size': 12, 'align': 'center', 'font': 'Arial', 'bottom': 1, 'top': 1, 'right': 1, 'left': 1})
h2 = workbook.add_format({'bold': 0, 'font_size': 10, 'font': 'Arial'})
h3 = workbook.add_format({'bold': 0, 'font_size': 9, 'font': 'Arial'})
f1 = workbook.add_format({'bold': 0, 'font_size': 9, 'font': 'Arial', 'align': 'right'})

cell_format1 = workbook.add_format({'bottom': 1, 'top': 1, 'font': 'Arial', 'font_size': 9, 'border': 7, 'right': 0, 'left': 0})
cell_formatL = workbook.add_format({'bottom': 1, 'top': 1, 'font': 'Arial', 'font_size': 9,  'right': 1,'border': 7, 'left': 0 })
cell_format = workbook.add_format(
    {'bold': 0, 'font_color': 'black', 'font': 'Arial', 'font_size': 9, 'bottom': 1, 'top': 1, 'right': 1, 'left': 1,
     'border': 7})

cell_format2 = workbook.add_format(
    {'bold': 0, 'align': 'center', 'font_color': 'black', 'font': 'Arial', 'font_size': 9, 'bottom': 1, 'top': 1,
     'right': 1, 'left': 1, 'border': 7})

cell_format3 = workbook.add_format(
{'bold': True, 'align': 'center', 'font_color': 'black', 'font': 'Arial', 'font_size': 12, 'bottom': 1, 'top': 1,
     'right': 1, 'left': 1, 'border': 7})

column_width = [{'name': 'A1:A73', 'size': 5}, {'name': 'B1:B73', 'size': 16.57}, {'name': 'C1:C73', 'size': 11},
                {'name': 'D1:D73', 'size': 12},
                {'name': 'E1:E73', 'size': 7.5}, {'name': 'F1:F73', 'size': 7}, {'name': 'G1:G73', 'size': 5},
                {'name': 'H1:H73', 'size': 9.5},
                {'name': 'I1:I73', 'size': 13}, {'name': 'J1:J73', 'size': 7.5}, {'name': 'K1:K73', 'size': 7},
                {'name': 'L1:L73', 'size': 6.5}, {'name': 'M1:M73', 'size': 8}]

for i in column_width:
    worksheet.set_column(i['name'], i['size'])

# worksheet.set_column('A1:A73', 5)
# worksheet.set_column('B1:B73', 24)
# worksheet.set_column('C1:C73', 10)
# worksheet.set_column('D1:D73', 12)
# worksheet.set_column('E1:E73', 7)
# worksheet.set_column('F1:F73', 5)
# worksheet.set_column('G1:G73', 12)
# worksheet.set_column('H1:H73', 12)
# worksheet.set_column('I1:I73', 6)
# worksheet.set_column('J1:J73', 6)
# worksheet.set_column('K1:K73', 6)
# worksheet.set_column('L1:L73', 6)

worksheet.insert_image('A4', 'Fcc logo.png', {'x_scale': 0.5, 'y_scale': 0.5})
worksheet.merge_range('A3:B7', "", cell_format)

worksheet.write('A1', '', )
worksheet.merge_range('A2:M2', 'Control Valve Specification Sheet', cell_format3)
worksheet.merge_range('A8:B8', "Application", cell_format)
worksheet.write('A9:B9', 'Fluid State / Name', cell_format)
worksheet.write('A10', 'AA', boldc)
worksheet.write('A11', '1', cell_format2)
worksheet.write('A12', '2', cell_format2)
worksheet.write('A13', '3', cell_format2)
worksheet.write('A14', '4', cell_format2)
worksheet.write('A15', '5', cell_format2)
worksheet.write('A16', '6', cell_format2)
worksheet.write('A17', '7', cell_format2)
worksheet.write('A18', '8', cell_format2)
worksheet.write('A19', '9', cell_format2)
worksheet.write('A20', '10', cell_format2)
worksheet.write('A21', '11', cell_format2)
worksheet.write('A22', '12', cell_format2)
worksheet.write('A23', '13', cell_format2)
worksheet.write('A24', '14', cell_format2)
worksheet.write('A25', '15', cell_format2)
# worksheet.write('A29', '')
worksheet.write('A26', 'BB', boldc)
worksheet.write('A27', '16', cell_format2)
worksheet.write('A28', '17', cell_format2)
worksheet.write('A29', '18', cell_format2)
worksheet.write('A30', '19', cell_format2)
worksheet.write('A31', '20', cell_format2)
worksheet.write('A32', 'CC', boldc)
worksheet.write('A33', '21', cell_format2)
worksheet.write('A34', '22', cell_format2)
worksheet.write('A35', '23', cell_format2)
worksheet.write('A36', '24', cell_format2)
worksheet.write('A37', '25', cell_format2)
worksheet.write('A38', '26', cell_format2)
worksheet.write('A39', '27', cell_format2)
worksheet.write('A40', '28', cell_format2)
worksheet.write('A41', '29', cell_format2)
worksheet.write('A42', '30', cell_format2)
worksheet.write('A43', '31', cell_format2)
worksheet.write('A44', '32', cell_format2)
worksheet.write('A45', '33', cell_format2)
worksheet.write('A46', '34', cell_format2)
worksheet.write('A47', 'DD', boldc)
worksheet.write('A48', '35', cell_format2)
worksheet.write('A49', '36', cell_format2)
worksheet.write('A50', '37', cell_format2)
worksheet.write('A51', '38', cell_format2)
worksheet.write('A52', '39', cell_format2)
worksheet.write('A53', '40', cell_format2)
worksheet.write('A54', '41', cell_format2)
worksheet.write('A55', '42', cell_format2)
worksheet.write('A56', '43', cell_format2)
worksheet.write('A57', 'HH', boldc)
worksheet.write('A58', '71', cell_format2)
worksheet.write('A59', '72', cell_format2)
worksheet.write('A60', '73', cell_format2)
worksheet.write('A61', '74', cell_format2)
worksheet.write('A62', '75', cell_format2)
worksheet.write('A63', '76', cell_format2)
worksheet.write('A64', '77', cell_format2)
worksheet.write('A65', '78', cell_format2)
worksheet.write('A66', '79', cell_format2)
worksheet.write('A67', '80', cell_format2)
worksheet.write('A68', '81', cell_format2)
worksheet.write('A69', '82', cell_format2)
worksheet.write('A70', '83', cell_format2)
worksheet.write('A71', '84', cell_format2)


worksheet.write('B2', '')
worksheet.write('B3', '')

worksheet.merge_range("B10:C10", 'Valve Sizing Calculation', bold)
worksheet.merge_range("B11:C11", 'Flow Rate', cell_format)
worksheet.merge_range("B12:C12", 'Inlet Pressure', cell_format)
worksheet.merge_range("B13:C13", 'Outlet Pressure', cell_format)
worksheet.merge_range("B14:C14", 'Inlet Temperature', cell_format)
worksheet.merge_range("B15:C15", 'Specific Gravity', cell_format)
worksheet.merge_range("B16:C16", 'Kinematic Viscosity', cell_format)
worksheet.merge_range("B17:C17", 'Vapour Pressure', cell_format)
worksheet.merge_range("B18:C18", 'Liquid Pr. Recovery factor, Fl', cell_format)
worksheet.merge_range("B19:C19", 'Calculated Cv', cell_format)
worksheet.merge_range("B20:C20", 'Percentage Opening / Degree', cell_format)
worksheet.merge_range("B21:C21", 'Noise level at 1m distance', cell_format)
worksheet.merge_range("B22:C22", 'Inlet Pipe Velocity', cell_format)
worksheet.merge_range("B23:C23", 'Outlet Pipe Velocity', cell_format)
worksheet.merge_range("B24:C24", 'Trim Exit Velocity', cell_format)
worksheet.merge_range("B25:C25", 'Warnings!!', cell_format)

worksheet.merge_range("B26:F26", 'Pipe Line Data', bold)
worksheet.merge_range("B27:C27", 'Size / Schedule Inlet', cell_format1)
worksheet.merge_range("B28:C28", 'Size / Schedule Oulet', cell_format1)
worksheet.merge_range("B29:C29", 'Insulation', cell_format1)
worksheet.merge_range("B30:C30", 'Design Pressure', cell_format1)
worksheet.merge_range("B31:C31", 'Design Temp. Min / Max', cell_format1)
worksheet.merge_range("B32:F32", 'Valve Body & Bonnet', bold)
worksheet.merge_range("B33:C33", 'Valve Mfg / Model No.', cell_format1)
worksheet.merge_range("B34:C34", 'Size / Rating', cell_format1)
worksheet.merge_range("B35:C35", 'Body Style', cell_format1)
worksheet.merge_range("B36:C36", 'Body Material', cell_format1)
worksheet.merge_range("B37:C37", 'End Connections', cell_format1)
worksheet.merge_range("B38:C38", 'End Finish / Preparation', cell_format1)
worksheet.merge_range("B39:C39", 'Body F/F Dim', cell_format1)
worksheet.merge_range("B40:C40", 'Bonnet Type', cell_format1)
worksheet.merge_range("B41:C41", 'Bonnet Material', cell_format1)
worksheet.merge_range("B42:C42", 'Extension dimension', cell_format1)
worksheet.merge_range("B43:C43", 'Body/Bonnet NDE1 / NDE2', cell_format1)
worksheet.merge_range("B44:C44", 'Bonnet Bolting', cell_format1)
worksheet.merge_range("B45:C45", 'Gasket Material', cell_format1)
worksheet.merge_range("B46:C46", 'Gland Packing', cell_format1)

worksheet.merge_range("B47:F47", 'Valve Trim', bold)

worksheet.merge_range("B48:C48", 'Trim Size / Type', cell_format1)
worksheet.merge_range("B49:C49", 'Rated CV / Characteristic', cell_format1)
worksheet.merge_range("B50:C50", 'Flow Direction / Balancing', cell_format1)
worksheet.merge_range("B51:C51", 'Stem Material', cell_format1)
worksheet.merge_range("B52:C52", 'Plug Material', cell_format1)
worksheet.merge_range("B53:C53", 'Seat Material', cell_format1)
worksheet.merge_range("B54:C54", 'Cage or Clamp Material', cell_format1)
worksheet.merge_range("B55:C55", 'Seat Leakage Class', cell_format1)
worksheet.merge_range("B56:C56", 'Bellows Material', cell_format1)
# worksheet.merge_range("B56:J56", 'Bellows Material', cell_format1)


worksheet.merge_range("B57:J57", 'Notes', bold)
worksheet.merge_range("B58:J58", 'N1- MPI-Body/Bnt Castings/Forgings to ASME B16.34 at Foundry/Forge', cell_format)
worksheet.merge_range("B59:J59", '', cell_format)
worksheet.merge_range("B60:J60", '', cell_format)
worksheet.merge_range("B61:J61", '', cell_format)
worksheet.merge_range("B62:J62", '', cell_format)
worksheet.merge_range("B63:J63", '', cell_format)
worksheet.merge_range("B64:J64", '', cell_format)
worksheet.merge_range("B65:J65", '', cell_format)
worksheet.merge_range("B66:J66", '', cell_format)
worksheet.merge_range("B67:J67", '', cell_format)
worksheet.merge_range("B68:J68", '', cell_format)
worksheet.merge_range("B69:J69", '', cell_format)
worksheet.merge_range("B70:J70", '', cell_format)
worksheet.merge_range("B71:J71", '', cell_format)
worksheet.write('C1', '')
# worksheet.write('C2', '')
worksheet.write('C3', 'Customer', cell_format)
worksheet.write('C4', 'Project', cell_format)
worksheet.write('C5', 'End User', cell_format)
worksheet.write('C6', 'RFQ No', cell_format)
worksheet.write('C7', 'PO No', cell_format)
worksheet.merge_range('C8:M8', '', cell_format)
worksheet.merge_range('C9:F9', '', cell_format)

# worksheet.write('D2', '')
worksheet.merge_range('D3:H3', '', cell_format)
worksheet.merge_range('D4:H4', '', cell_format)
worksheet.merge_range('D5:H5', '', cell_format)
worksheet.merge_range('D6:H6', '', cell_format)
worksheet.merge_range('D7:H7', '', cell_format)

worksheet.write('D10', 'Units', bold)
worksheet.write('D11', '', cell_format)
worksheet.write('D12', '', cell_format)
worksheet.write('D13', '', cell_format)
worksheet.write('D14', '', cell_format)
worksheet.write('D15', '', cell_format)
worksheet.write('D16', '', cell_format)
worksheet.write('D17', '', cell_format)
worksheet.write('D18', '', cell_format)
worksheet.write('D19', '', cell_format)
worksheet.write('D20', '', cell_format)
worksheet.write('D21', '', cell_format)
worksheet.write('D22', '', cell_format)
worksheet.write('D23', '', cell_format)
worksheet.write('D24', '', cell_format)
worksheet.merge_range("D25:M25", '', cell_format)
# worksheet.write('D26', '', cell_format)
worksheet.write('D27', '', cell_format1)
worksheet.write('D28', '', cell_format1)
worksheet.write('D29', '', cell_format1)
worksheet.write('D30', '', cell_format1)
worksheet.write('D31', '', cell_format1)
# worksheet.write('D32', '', cell_format1)
worksheet.write('D33', '', cell_format1)
worksheet.write('D34', '', cell_format1)
worksheet.write('D35', '', cell_format1)
worksheet.write('D36', '', cell_format1)
worksheet.write('D37', '', cell_format1)
worksheet.write('D38', '', cell_format1)
worksheet.write('D39', '', cell_format1)
worksheet.write('D40', '', cell_format1)
worksheet.write('D41', '', cell_format1)
worksheet.write('D42', '', cell_format1)
worksheet.write('D43', '', cell_format1)
worksheet.write('D44', '', cell_format1)
worksheet.write('D45', '', cell_format1)
worksheet.write('D46', '', cell_format1)
# worksheet.write('D47', '', cell_format1)
worksheet.write('D48', '', cell_format1)
worksheet.write('D49', '', cell_format1)
worksheet.write('D50', '', cell_format1)
worksheet.write('D51', '', cell_format1)
worksheet.write('D52', '', cell_format1)
worksheet.write('D53', '', cell_format1)
worksheet.write('D54', '', cell_format1)
worksheet.write('D55', '', cell_format1)
# worksheet.write('D56', '', cell_format1)



worksheet.write('E27', '', cell_format1)
worksheet.write('E28', '', cell_format1)
worksheet.write('E29', '', cell_format1)
worksheet.write('E30', '', cell_format1)
worksheet.write('E31', '', cell_format1)
# worksheet.write('E32', '', cell_format1)
worksheet.write('E33', '', cell_format1)
worksheet.write('E34', '', cell_format1)
worksheet.write('E35', '', cell_format1)
worksheet.write('E36', '', cell_format1)
worksheet.write('E37', '', cell_format1)
worksheet.write('E38', '', cell_format1)
worksheet.write('E39', '', cell_format1)
worksheet.write('E40', '', cell_format1)
worksheet.write('E41', '', cell_format1)
worksheet.write('E42', '', cell_format1)
worksheet.write('E43', '', cell_format1)
worksheet.write('E44', '', cell_format1)
worksheet.write('E45', '', cell_format1)
worksheet.write('E46', '', cell_format1)
# worksheet.write('E47', '', cell_format1)
worksheet.write('E48', '', cell_format1)
worksheet.write('E49', '', cell_format1)
worksheet.write('E50', '', cell_format1)
worksheet.write('E51', '', cell_format1)
worksheet.write('E52', '', cell_format1)
worksheet.write('E53', '', cell_format1)
worksheet.write('E54', '', cell_format1)
worksheet.write('E55', '', cell_format1)



worksheet.merge_range("E10:F10", 'Case 1', bold)
worksheet.merge_range("E11:F11", '', cell_format)
worksheet.merge_range("E12:F12", '', cell_format)
worksheet.merge_range("E13:F13", '', cell_format)
worksheet.merge_range("E14:F14", '', cell_format)
worksheet.merge_range("E15:F15", '', cell_format)
worksheet.merge_range("E16:F16", '', cell_format)
worksheet.merge_range("E17:F17", '', cell_format)
worksheet.merge_range("E18:F18", '', cell_format)
worksheet.merge_range("E19:F19", '', cell_format)
worksheet.merge_range("E20:F20", '', cell_format)
worksheet.merge_range("E21:F21", '', cell_format)
worksheet.merge_range("E22:F22", '', cell_format)
worksheet.merge_range("E23:F23", '', cell_format)
worksheet.merge_range("E24:F24", '', cell_format)


worksheet.write('F27', '', cell_format1)
worksheet.write('F28', '', cell_format1)
worksheet.write('F29', '', cell_format1)
worksheet.write('F30', '', cell_format1)
worksheet.write('F31', '', cell_format1)
# worksheet.write('F32', '', cell_format1)
worksheet.write('F33', '', cell_format1)
worksheet.write('F34', '', cell_format1)
worksheet.write('F35', '', cell_format1)
worksheet.write('F36', '', cell_format1)
worksheet.write('F37', '', cell_format1)
worksheet.write('F38', '', cell_format1)
worksheet.write('F39', '', cell_format1)
worksheet.write('F40', '', cell_format1)
worksheet.write('F41', '', cell_format1)
worksheet.write('F42', '', cell_format1)
worksheet.write('F43', '', cell_format1)
worksheet.write('F44', '', cell_format1)
worksheet.write('F45', '', cell_format1)
worksheet.write('F46', '', cell_format1)
# worksheet.write('F47', '', cell_format1)
worksheet.write('F48', '', cell_format1)
worksheet.write('F49', '', cell_format1)
worksheet.write('F50', '', cell_format1)
worksheet.write('F51', '', cell_format1)
worksheet.write('F52', '', cell_format1)
worksheet.write('F53', '', cell_format1)
worksheet.write('F54', '', cell_format1)
worksheet.write('F55', '', cell_format1)



worksheet.write('G1', '', )
worksheet.write('G2', '', )
worksheet.write('G8', '', )
worksheet.merge_range("G9:H9", 'Critical Pressure.', cell_format)
worksheet.merge_range("G10:H10", 'Case 2', bold)
worksheet.merge_range("G11:H11", '', cell_format)
worksheet.merge_range("G12:H12", '', cell_format)
worksheet.merge_range("G13:H13", '', cell_format)
worksheet.merge_range("G14:H14", '', cell_format)
worksheet.merge_range("G15:H15", '', cell_format)
worksheet.merge_range("G16:H16", '', cell_format)
worksheet.merge_range("G17:H17", '', cell_format)
worksheet.merge_range("G18:H18", '', cell_format)
worksheet.merge_range("G19:H19", '', cell_format)
worksheet.merge_range("G20:H20", '', cell_format)
worksheet.merge_range("G21:H21", '', cell_format)
worksheet.merge_range("G22:H22", '', cell_format)
worksheet.merge_range("G23:H23", '', cell_format)
worksheet.merge_range("G24:H24", '', cell_format)
# worksheet.write('G25', '',)
worksheet.write('G26', 'BB', boldc)
worksheet.write('G27', '44', cell_format2)
worksheet.write('G28', '45', cell_format2)
worksheet.write('G29', '46', cell_format2)
worksheet.write('G30', '47', cell_format2)
worksheet.write('G31', '48', cell_format2)
worksheet.write('G32', '49', cell_format2)
worksheet.write('G33', '50', cell_format2)
worksheet.write('G34', '51', cell_format2)
worksheet.write('G35', '52', cell_format2)
worksheet.write('G36', '53', cell_format2)
worksheet.write('G37', '54', cell_format2)
worksheet.write('G38', 'FF', boldc)
worksheet.write('G39', '55', cell_format2)
worksheet.write('G40', '56', cell_format2)
worksheet.write('G41', '57', cell_format2)
worksheet.write('G42', '58', cell_format2)
worksheet.write('G43', '59', cell_format2)
worksheet.write('G44', '60', cell_format2)
worksheet.write('G45', '61', cell_format2)
worksheet.write('G46', '62', cell_format2)
worksheet.write('G47', '63', cell_format2)
worksheet.write('G48', '64', cell_format2)
worksheet.write('G49', '65', cell_format2)
worksheet.write('G50', '66', cell_format2)
worksheet.write('G51', 'GG', boldc)
worksheet.write('G52', '67', cell_format2)
worksheet.write('G53', '68', cell_format2)
worksheet.write('G54', '69', cell_format2)
worksheet.write('G55', '70', cell_format2)
worksheet.write('G56', '', cell_format2)


worksheet.merge_range("H26:M26", 'Actuator Data', bold)
worksheet.merge_range("H27:I27", "Actuator Type", cell_format1)
worksheet.merge_range("H28:I28", "Actuator Model No. / Travel", cell_format1)
worksheet.merge_range("H29:I29", "Actuator Size / Spring", cell_format1)
worksheet.merge_range("H30:I30", "Air Fail Action", cell_format1)
worksheet.merge_range("H31:I31", 'Air Supply / Set pressure', cell_format1)
worksheet.merge_range("H32:I32", 'Actuator Orientation', cell_format1)
worksheet.merge_range("H33:I33", 'Handwheel', cell_format1)
worksheet.merge_range("H34:I34", 'Travel Stops', cell_format1)
worksheet.merge_range("H35:I35", 'Tubing make / Size', cell_format1)
worksheet.merge_range("H36:I36", 'Fittings', cell_format1)
worksheet.merge_range("H37:I37", 'Open / Close / Trip Time', cell_format1)
worksheet.merge_range("H38:M38", 'Accessories & Tubing', bold)
worksheet.merge_range("H39:I39", 'Positioner Mfg / Model', cell_format1)
worksheet.merge_range("H40:I40", 'Signal Action', cell_format1)
worksheet.merge_range("H41:I41", 'AFR Mfg / Model', cell_format1)
worksheet.merge_range("H42:I42", 'Position Transmitter', cell_format1)
worksheet.merge_range("H43:I43", 'Limit switch / Proximity switch', cell_format1)
worksheet.merge_range("H44:I44", 'Boosters', cell_format1)
worksheet.merge_range("H45:I45", 'Pilot Valves', cell_format1)
worksheet.merge_range("H46:I46", 'Air Lock Relay', cell_format1)
worksheet.merge_range("H47:I47", 'I/P converter Mfg / Model', cell_format1)
worksheet.merge_range("H48:I48", 'Solenoid Valve Mfg / Model', cell_format1)
worksheet.merge_range("H49:I49", 'Solenoid Action', cell_format1)
worksheet.merge_range("H50:I50", 'Volume Tank', cell_format1)
worksheet.merge_range("H51:M51", 'Testing, Certification, Cleaning, Painting', bold)
worksheet.merge_range("H52:I52", 'Testing', cell_format1)
worksheet.merge_range("H53:I53", 'Assembly cleaning procedure', cell_format1)
worksheet.merge_range("H54:I54", 'Painting Specification', cell_format1)
worksheet.merge_range("H55:I55", 'Product Certification', cell_format1)

worksheet.write('I1', '')
worksheet.write('I2', '')
worksheet.write('I3', 'Quote No', cell_format)
worksheet.write('I4', 'W/O No', cell_format)
worksheet.write('I5', 'Serial No', cell_format)
worksheet.write('I6', 'Tag No', cell_format)
worksheet.write('I7', 'Item No / Qty', cell_format)
# worksheet.write('I8', '', cell_format)
worksheet.write('I9', '', cell_format)
worksheet.write('I10', 'Case 3', bold)
worksheet.write('I11', '', cell_format)
worksheet.write('I12', '', cell_format)
worksheet.write('I13', '', cell_format)
worksheet.write('I14', '', cell_format)
worksheet.write('I15', '', cell_format)
worksheet.write('I16', '', cell_format)
worksheet.write('I17', '', cell_format)
worksheet.write('I18', '', cell_format)
worksheet.write('I19', '', cell_format)
worksheet.write('I20', '', cell_format)
worksheet.write('I21', '', cell_format)
worksheet.write('I22', '', cell_format)
worksheet.write('I23', '', cell_format)
worksheet.write('I24', '', cell_format)
# worksheet.write('I25', '', cell_format)

worksheet.write('J27', '', cell_format1)
worksheet.write('J28', '', cell_format1)
worksheet.write('J29', '', cell_format1)
worksheet.write('J30', '', cell_format1)
worksheet.write('J31', '', cell_format1)
worksheet.write('J32', '', cell_format1)
worksheet.write('J33', '', cell_format1)
worksheet.write('J34', '', cell_format1)
worksheet.write('J35', '', cell_format1)
worksheet.write('J36', '', cell_format1)
worksheet.write('J37', '', cell_format1)
# worksheet.write('J38', '', cell_format1)
worksheet.write('J39', '', cell_format1)
worksheet.write('J40', '', cell_format1)
worksheet.write('J41', '', cell_format1)
worksheet.write('J42', '', cell_format1)
worksheet.write('J43', '', cell_format1)
worksheet.write('J44', '', cell_format1)
worksheet.write('J45', '', cell_format1)
worksheet.write('J46', '', cell_format1)
worksheet.write('J47', '', cell_format1)
worksheet.write('J48', '', cell_format1)
worksheet.write('J49', '', cell_format1)
worksheet.write('J50', '', cell_format1)
# worksheet.write('J51', '', cell_format1)
worksheet.write('J52', '', cell_format1)
worksheet.write('J53', '', cell_format1)
worksheet.write('J54', '', cell_format1)
worksheet.write('J55', '', cell_format1)


worksheet.write('K27', '', cell_format1)
worksheet.write('K28', '', cell_format1)
worksheet.write('K29', '', cell_format1)
worksheet.write('K30', '', cell_format1)
worksheet.write('K31', '', cell_format1)
worksheet.write('K32', '', cell_format1)
worksheet.write('K33', '', cell_format1)
worksheet.write('K34', '', cell_format1)
worksheet.write('K35', '', cell_format1)
worksheet.write('K36', '', cell_format1)
worksheet.write('K37', '', cell_format1)
# worksheet.write('K38', '', cell_format1)
worksheet.write('K39', '', cell_format1)
worksheet.write('K40', '', cell_format1)
worksheet.write('K41', '', cell_format1)
worksheet.write('K42', '', cell_format1)
worksheet.write('K43', '', cell_format1)
worksheet.write('K44', '', cell_format1)
worksheet.write('K45', '', cell_format1)
worksheet.write('K46', '', cell_format1)
worksheet.write('K47', '', cell_format1)
worksheet.write('K48', '', cell_format1)
worksheet.write('K49', '', cell_format1)
worksheet.write('K50', '', cell_format1)
# worksheet.write('K51', '', cell_format1)
worksheet.write('K52', '', cell_format1)
worksheet.write('K53', '', cell_format1)
worksheet.write('K54', '', cell_format1)
worksheet.write('K55', '', cell_format1)

worksheet.merge_range("J3:M3", '', cell_format)
worksheet.merge_range("J4:M4", '', cell_format)
worksheet.merge_range("J5:M5", '', cell_format)
worksheet.merge_range("J6:M6", '', cell_format)
# worksheet.merge_range("J7:M7", '', cell_format)
worksheet.merge_range("J9:K9", 'Shutoff Pressure.', cell_format)
worksheet.merge_range("J10:K10", 'Case 4', bold)
worksheet.merge_range("J11:K11", '', cell_format)
worksheet.merge_range("J12:K12", '', cell_format)
worksheet.merge_range("J13:K13", '', cell_format)
worksheet.merge_range("J14:K14", '', cell_format)
worksheet.merge_range("J15:K15", '', cell_format)
worksheet.merge_range("J16:K16", '', cell_format)
worksheet.merge_range("J17:K17", '', cell_format)
worksheet.merge_range("J18:K18", '', cell_format)
worksheet.merge_range("J19:K19", '', cell_format)
worksheet.merge_range("J20:K20", '', cell_format)
worksheet.merge_range("J21:K21", '', cell_format)
worksheet.merge_range("J22:K22", '', cell_format)
worksheet.merge_range("J23:K23", '', cell_format)
worksheet.merge_range("J24:K24", '', cell_format)
worksheet.write('L27', '', cell_format1)
worksheet.write('L28', '', cell_format1)
worksheet.write('L29', '', cell_format1)
worksheet.write('L30', '', cell_format1)
worksheet.write('L31', '', cell_format1)
worksheet.write('L32', '', cell_format1)
worksheet.write('L33', '', cell_format1)
worksheet.write('L34', '', cell_format1)
worksheet.write('L35', '', cell_format1)
worksheet.write('L36', '', cell_format1)
worksheet.write('L37', '', cell_format1)
# worksheet.write('L38', '', cell_format1)
worksheet.write('L39', '', cell_format1)
worksheet.write('L40', '', cell_format1)
worksheet.write('L41', '', cell_format1)
worksheet.write('L42', '', cell_format1)
worksheet.write('L43', '', cell_format1)
worksheet.write('L44', '', cell_format1)
worksheet.write('L45', '', cell_format1)
worksheet.write('L46', '', cell_format1)
worksheet.write('L47', '', cell_format1)
worksheet.write('L48', '', cell_format1)
worksheet.write('L49', '', cell_format1)
worksheet.write('L50', '', cell_format1)
# worksheet.write('L51', '', cell_format1)
worksheet.write('L52', '', cell_format1)
worksheet.write('L53', '', cell_format1)
worksheet.write('L54', '', cell_format1)
worksheet.write('L55', '', cell_format1)

worksheet.write('M27', '', cell_formatL)
worksheet.write('M28', '', cell_formatL)
worksheet.write('M29', '', cell_formatL)
worksheet.write('M30', '', cell_formatL)
worksheet.write('M31', '', cell_formatL)
worksheet.write('M32', '', cell_formatL)
worksheet.write('M33', '', cell_formatL)
worksheet.write('M34', '', cell_formatL)
worksheet.write('M35', '', cell_formatL)
worksheet.write('M36', '', cell_formatL)
worksheet.write('M37', '', cell_formatL)
# worksheet.write('M38', '', cell_formatL)
worksheet.write('M39', '', cell_formatL)
worksheet.write('M40', '', cell_formatL)
worksheet.write('M41', '', cell_formatL)
worksheet.write('M42', '', cell_formatL)
worksheet.write('M43', '', cell_formatL)
worksheet.write('M44', '', cell_formatL)
worksheet.write('M45', '', cell_formatL)
worksheet.write('M46', '', cell_formatL)
worksheet.write('M47', '', cell_formatL)
worksheet.write('M48', '', cell_formatL)
worksheet.write('M49', '', cell_formatL)
worksheet.write('M50', '', cell_formatL)
# worksheet.write('M51', '', cell_formatL)
worksheet.write('M52', '', cell_formatL)
worksheet.write('M53', '', cell_formatL)
worksheet.write('M54', '', cell_formatL)
worksheet.write('M55', '', cell_formatL)

worksheet.merge_range("L9:M9", '', cell_format)
worksheet.merge_range("L10:M10", 'Case 5', bold)
worksheet.merge_range("L11:M11", '', cell_format)
worksheet.merge_range("L12:M12", '', cell_format)
worksheet.merge_range("L13:M13", '', cell_format)
worksheet.merge_range("L14:M14", '', cell_format)
worksheet.merge_range("L15:M15", '', cell_format)
worksheet.merge_range("L16:M16", '', cell_format)
worksheet.merge_range("L17:M17", '', cell_format)
worksheet.merge_range("L18:M18", '', cell_format)
worksheet.merge_range("L19:M19", '', cell_format)
worksheet.merge_range("L20:M20", '', cell_format)
worksheet.merge_range("L21:M21", '', cell_format)
worksheet.merge_range("L22:M22", '', cell_format)
worksheet.merge_range("L23:M23", '', cell_format)
worksheet.merge_range("L24:M24", '', cell_format)

worksheet.merge_range("K57:M57", 'Revision Control', bold)
worksheet.write('J57', '', cell_format)
worksheet.write('K58', 'Rev.', cell_format)

# worksheet.write('J58', 'Rev.', cell_format)
worksheet.write('J59', '', cell_format)
worksheet.write('J60', '', cell_format)
worksheet.write('J61', '', cell_format)
worksheet.write('J62', '', cell_format)
worksheet.write('J63', '', cell_format)
worksheet.write('J64', '', cell_format)
worksheet.write('J65', '', cell_format)
worksheet.write('J66', '', cell_format)
worksheet.write('J67', '', cell_format)
worksheet.write('J68', '', cell_format)
worksheet.write('J69', '', cell_format)
worksheet.write('J70', '', cell_format)
worksheet.write('J71', '', cell_format)

# worksheet.write('K58', '', cell_format)
worksheet.write('K59', '', cell_format)
worksheet.write('K60', '', cell_format)
worksheet.write('K61', '', cell_format)
worksheet.write('K62', '', cell_format)
worksheet.write('K63', '', cell_format)
worksheet.write('K64', '', cell_format)
worksheet.write('K65', '', cell_format)
worksheet.write('K66', '', cell_format)
worksheet.write('K67', '', cell_format)
worksheet.write('K68', '', cell_format)
worksheet.write('K69', '', cell_format)
worksheet.write('K70', '', cell_format)
worksheet.write('K71', '', cell_format)

# worksheet.write('L57', '', cell_format)
worksheet.write('L58', 'By', cell_format)
worksheet.write('L59', '', cell_format)
worksheet.write('L60', '', cell_format)
worksheet.write('L61', '', cell_format)
worksheet.write('L62', '', cell_format)
worksheet.write('L63', '', cell_format)
worksheet.write('L64', '', cell_format)
worksheet.write('L65', '', cell_format)
worksheet.write('L66', '', cell_format)
worksheet.write('L67', '', cell_format)
worksheet.write('L68', '', cell_format)
worksheet.write('L69', '', cell_format)
worksheet.write('L70', '', cell_format)
worksheet.write('L71', '', cell_format)

worksheet.write('M56', '', cell_formatL)
worksheet.write('M7', '', cell_formatL)
# worksheet.write('M57', '', cell_format)
worksheet.write('M58', 'Date', cell_format)
worksheet.write('M59', '', cell_format)
worksheet.write('M60', '', cell_format)
worksheet.write('M61', '', cell_format)
worksheet.write('M62', '', cell_format)
worksheet.write('M63', '', cell_format)
worksheet.write('M64', '', cell_format)
worksheet.write('M65', '', cell_format)
worksheet.write('M66', '', cell_format)
worksheet.write('M67', '', cell_format)
worksheet.write('M68', '', cell_format)
worksheet.write('M69', '', cell_format)
worksheet.write('M70', '', cell_format)
worksheet.write('M71', '', cell_format)

worksheet.write('A72', 'FLOW CONTROL COMMUNE', )
worksheet.write('M72', 'FR/AE/004', f1)

workbook.close()