"""Initial migration.

Revision ID: 92c4622a98da
Revises: 
Create Date: 2023-12-11 12:53:10.543604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c4622a98da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accessoriesData')
    op.drop_table('Users')
    with op.batch_alter_table('itemCases', schema=None) as batch_op:
        batch_op.alter_column('fluidName',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemCases', schema=None) as batch_op:
        batch_op.alter_column('fluidName',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accessoriesData',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=200), nullable=True),
    sa.Column('model', sa.VARCHAR(length=200), nullable=True),
    sa.Column('action', sa.VARCHAR(length=200), nullable=True),
    sa.Column('afr', sa.VARCHAR(length=200), nullable=True),
    sa.Column('transmitter', sa.VARCHAR(length=200), nullable=True),
    sa.Column('limit', sa.VARCHAR(length=200), nullable=True),
    sa.Column('proximity', sa.VARCHAR(length=200), nullable=True),
    sa.Column('booster', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pilot_valve', sa.VARCHAR(length=200), nullable=True),
    sa.Column('air_lock', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ip_make', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ip_model', sa.VARCHAR(length=200), nullable=True),
    sa.Column('solenoid_make', sa.VARCHAR(length=200), nullable=True),
    sa.Column('solenoid_model', sa.VARCHAR(length=200), nullable=True),
    sa.Column('solenoid_action', sa.VARCHAR(length=200), nullable=True),
    sa.Column('volume_tank', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ip_converter', sa.VARCHAR(length=200), nullable=True),
    sa.Column('air_receiver', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tubing', sa.VARCHAR(length=200), nullable=True),
    sa.Column('fittings', sa.VARCHAR(length=200), nullable=True),
    sa.Column('cleaning', sa.VARCHAR(length=200), nullable=True),
    sa.Column('certification', sa.VARCHAR(length=200), nullable=True),
    sa.Column('paint_finish', sa.VARCHAR(length=200), nullable=True),
    sa.Column('paint_cert', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sp1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sp2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sp3', sa.VARCHAR(length=200), nullable=True),
    sa.Column('rm', sa.VARCHAR(length=200), nullable=True),
    sa.Column('hydro', sa.VARCHAR(length=200), nullable=True),
    sa.Column('final', sa.VARCHAR(length=200), nullable=True),
    sa.Column('paint_inspect', sa.VARCHAR(length=200), nullable=True),
    sa.Column('packing_inspect', sa.VARCHAR(length=200), nullable=True),
    sa.Column('vt1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('vt2', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
